// Code generated by AI agent with mus-skill. DO NOT EDIT.

package safe

import (
	"github.com/mus-format/mus-go/ord"
	"github.com/mus-format/mus-go/raw"
	"github.com/mus-format/mus-go/unsafe"
	"github.com/mus-format/mus-go/varint"
	"github.com/mus-format/mus-skill-go/test/mode"
)

// FullDefinedMUS
var FullDefinedMUS = fullDefinedMUS{}

type fullDefinedMUS struct{}

func (s fullDefinedMUS) Marshal(v mode.FullDefined, bs []byte) (n int) {
	return varint.Int.Marshal(int(v), bs)
}

func (s fullDefinedMUS) Unmarshal(bs []byte) (v mode.FullDefined, n int, err error) {
	tmp, n, err := varint.Int.Unmarshal(bs)
	if err != nil {
		return
	}
	v = mode.FullDefined(tmp)
	return
}

func (s fullDefinedMUS) Size(v mode.FullDefined) (size int) {
	return varint.Int.Size(int(v))
}

func (s fullDefinedMUS) Skip(bs []byte) (n int, err error) {
	return varint.Int.Skip(bs)
}

// FullInterfaceImplMUS
var FullInterfaceImplMUS = fullInterfaceImplMUS{}

type fullInterfaceImplMUS struct{}

func (s fullInterfaceImplMUS) Marshal(v mode.FullInterfaceImpl, bs []byte) (n int) {
	return ord.String.Marshal(string(v), bs)
}

func (s fullInterfaceImplMUS) Unmarshal(bs []byte) (v mode.FullInterfaceImpl, n int, err error) {
	tmp, n, err := ord.String.Unmarshal(bs)
	if err != nil {
		return
	}
	v = mode.FullInterfaceImpl(tmp)
	return
}

func (s fullInterfaceImplMUS) Size(v mode.FullInterfaceImpl) (size int) {
	return ord.String.Size(string(v))
}

func (s fullInterfaceImplMUS) Skip(bs []byte) (n int, err error) {
	return ord.String.Skip(bs)
}

// Anonymous serializers
var (
	ptr2778Wd8dLOYluvJEYUJm8gΞΞ   = ord.NewPtrSer(varint.Int)
	array2778Wd8dLOYluvJEYUJm8gΞΞ = unsafe.NewArraySer[[10]int, int](varint.Int)
	slice2778Wd8dLOYluvJEYUJm8gΞΞ = ord.NewSliceSer(varint.Int)
	mapgrpYXw8V9l38S7utX2ΣMNAΞΞ   = ord.NewMapSer(ord.String, varint.Int)
)

// FullStructMUS
var FullStructMUS = fullStructMUS{}

type fullStructMUS struct{}

func (s fullStructMUS) Marshal(v mode.FullStruct, bs []byte) (n int) {
	n = varint.Int.Marshal(v.Int, bs)
	n += varint.Int64.Marshal(v.Int64, bs[n:])
	n += varint.Int32.Marshal(v.Int32, bs[n:])
	n += varint.Int16.Marshal(v.Int16, bs[n:])
	n += varint.Int8.Marshal(v.Int8, bs[n:])
	n += varint.Uint.Marshal(v.Uint, bs[n:])
	n += varint.Uint64.Marshal(v.Uint64, bs[n:])
	n += varint.Uint32.Marshal(v.Uint32, bs[n:])
	n += varint.Uint16.Marshal(v.Uint16, bs[n:])
	n += raw.Uint8.Marshal(v.Uint8, bs[n:])
	n += raw.Float64.Marshal(v.Float64, bs[n:])
	n += raw.Float32.Marshal(v.Float32, bs[n:])
	n += raw.Uint8.Marshal(v.Byte, bs[n:])
	n += ord.Bool.Marshal(v.Bool, bs[n:])
	n += ord.String.Marshal(v.Str, bs[n:])
	n += ord.ByteSlice.Marshal(v.ByteSlice, bs[n:])
	n += ord.ByteSlice.Marshal(v.Uint8Slice, bs[n:])
	n += raw.TimeUnixUTC.Marshal(v.Time, bs[n:])
	n += ptr2778Wd8dLOYluvJEYUJm8gΞΞ.Marshal(v.PtrInt, bs[n:])
	n += array2778Wd8dLOYluvJEYUJm8gΞΞ.Marshal(v.ArrayInt, bs[n:])
	n += slice2778Wd8dLOYluvJEYUJm8gΞΞ.Marshal(v.SliceInt, bs[n:])
	n += mapgrpYXw8V9l38S7utX2ΣMNAΞΞ.Marshal(v.MapStrInt, bs[n:])
	n += FullDefinedMUS.Marshal(v.Defined, bs[n:])
	return n
}

func (s fullStructMUS) Unmarshal(bs []byte) (v mode.FullStruct, n int, err error) {
	var n1 int
	v.Int, n1, err = varint.Int.Unmarshal(bs)
	n += n1
	if err != nil {
		return
	}
	v.Int64, n1, err = varint.Int64.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Int32, n1, err = varint.Int32.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Int16, n1, err = varint.Int16.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Int8, n1, err = varint.Int8.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Uint, n1, err = varint.Uint.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Uint64, n1, err = varint.Uint64.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Uint32, n1, err = varint.Uint32.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Uint16, n1, err = varint.Uint16.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Uint8, n1, err = raw.Uint8.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Float64, n1, err = raw.Float64.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Float32, n1, err = raw.Float32.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Byte, n1, err = raw.Uint8.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Bool, n1, err = ord.Bool.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Str, n1, err = ord.String.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.ByteSlice, n1, err = ord.ByteSlice.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Uint8Slice, n1, err = ord.ByteSlice.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Time, n1, err = raw.TimeUnixUTC.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.PtrInt, n1, err = ptr2778Wd8dLOYluvJEYUJm8gΞΞ.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.ArrayInt, n1, err = array2778Wd8dLOYluvJEYUJm8gΞΞ.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.SliceInt, n1, err = slice2778Wd8dLOYluvJEYUJm8gΞΞ.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.MapStrInt, n1, err = mapgrpYXw8V9l38S7utX2ΣMNAΞΞ.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Defined, n1, err = FullDefinedMUS.Unmarshal(bs[n:])
	n += n1
	return
}

func (s fullStructMUS) Size(v mode.FullStruct) (size int) {
	size = varint.Int.Size(v.Int)
	size += varint.Int64.Size(v.Int64)
	size += varint.Int32.Size(v.Int32)
	size += varint.Int16.Size(v.Int16)
	size += varint.Int8.Size(v.Int8)
	size += varint.Uint.Size(v.Uint)
	size += varint.Uint64.Size(v.Uint64)
	size += varint.Uint32.Size(v.Uint32)
	size += varint.Uint16.Size(v.Uint16)
	size += raw.Uint8.Size(v.Uint8)
	size += raw.Float64.Size(v.Float64)
	size += raw.Float32.Size(v.Float32)
	size += raw.Uint8.Size(v.Byte)
	size += ord.Bool.Size(v.Bool)
	size += ord.String.Size(v.Str)
	size += ord.ByteSlice.Size(v.ByteSlice)
	size += ord.ByteSlice.Size(v.Uint8Slice)
	size += raw.TimeUnixUTC.Size(v.Time)
	size += ptr2778Wd8dLOYluvJEYUJm8gΞΞ.Size(v.PtrInt)
	size += array2778Wd8dLOYluvJEYUJm8gΞΞ.Size(v.ArrayInt)
	size += slice2778Wd8dLOYluvJEYUJm8gΞΞ.Size(v.SliceInt)
	size += mapgrpYXw8V9l38S7utX2ΣMNAΞΞ.Size(v.MapStrInt)
	size += FullDefinedMUS.Size(v.Defined)
	return size
}

func (s fullStructMUS) Skip(bs []byte) (n int, err error) {
	var n1 int
	n1, err = varint.Int.Skip(bs)
	n += n1
	if err != nil {
		return
	}
	n1, err = varint.Int64.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = varint.Int32.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = varint.Int16.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = varint.Int8.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = varint.Uint.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = varint.Uint64.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = varint.Uint32.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = varint.Uint16.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = raw.Uint8.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = raw.Float64.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = raw.Float32.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = raw.Uint8.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.Bool.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.String.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.ByteSlice.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.ByteSlice.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = raw.TimeUnixUTC.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = ptr2778Wd8dLOYluvJEYUJm8gΞΞ.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = array2778Wd8dLOYluvJEYUJm8gΞΞ.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = slice2778Wd8dLOYluvJEYUJm8gΞΞ.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = mapgrpYXw8V9l38S7utX2ΣMNAΞΞ.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = FullDefinedMUS.Skip(bs[n:])
	n += n1
	return
}
