// Code generated by AI agent with mus-skill. DO NOT EDIT.

package pkg

import (
	"image"

	"github.com/mus-format/mus-go/varint"
)

// PointMUS
var PointMUS = pointMUS{}

type pointMUS struct{}

func (s pointMUS) Marshal(v image.Point, bs []byte) (n int) {
	n = varint.Int.Marshal(v.X, bs)
	n += varint.Int.Marshal(v.Y, bs[n:])
	return n
}

func (s pointMUS) Unmarshal(bs []byte) (v image.Point, n int, err error) {
	var n1 int
	v.X, n, err = varint.Int.Unmarshal(bs)
	if err != nil {
		return
	}
	v.Y, n1, err = varint.Int.Unmarshal(bs[n:])
	n += n1
	return
}

func (s pointMUS) Size(v image.Point) (size int) {
	size = varint.Int.Size(v.X)
	size += varint.Int.Size(v.Y)
	return size
}

func (s pointMUS) Skip(bs []byte) (n int, err error) {
	var n1 int
	n, err = varint.Int.Skip(bs)
	if err != nil {
		return
	}
	n1, err = varint.Int.Skip(bs[n:])
	n += n1
	return
}
