// Code generated by AI agent with mus-skill. DO NOT EDIT.

package pkg

import (
	"image"
	"testing"

	"github.com/mus-format/mus-go/test"
)

func TestPoint(t *testing.T) {
	cases := []image.Point{
		{X: 0, Y: 0},
		{X: 1, Y: 1},
		{X: -1, Y: -1},
		{X: 100, Y: 200},
	}
	test.Test(cases, PointMUS, t)
	test.TestSkip(cases, PointMUS, t)
}
