// Code generated by the AI agent with mus-skill-go. DO NOT EDIT.

package sub

import (
	"github.com/mus-format/mus-go/varint"
	userhints "github.com/mus-format/mus-skill-go/test/mus-go/user_hints"
)

var CrossPackageMUS = crossPackageMUS{}

type crossPackageMUS struct{}

func (s crossPackageMUS) Marshal(v userhints.CrossPackage, bs []byte) (n int) {
	return varint.Int.Marshal(int(v), bs)
}

func (s crossPackageMUS) Unmarshal(bs []byte) (v userhints.CrossPackage, n int, err error) {
	v1, n, err := varint.Int.Unmarshal(bs)
	v = userhints.CrossPackage(v1)
	return
}

func (s crossPackageMUS) Size(v userhints.CrossPackage) (size int) {
	return varint.Int.Size(int(v))
}

func (s crossPackageMUS) Skip(bs []byte) (n int, err error) {
	return varint.Int.Skip(bs)
}
