// Code generated by AI agent with mus-skill. DO NOT EDIT.

package test

import (
	"testing"

	"github.com/mus-format/mus-go/test"
)

func TestLenString(t *testing.T) {
	var (
		ser   = LenStringMUS
		cases = []LenString{"", "hello", "world"}
	)
	test.Test(cases, ser, t)
	test.TestSkip(cases, ser, t)
}

func TestLenSlice(t *testing.T) {
	var (
		ser   = LenSliceMUS
		cases = []LenSlice{{}, {1, 2, 3}, {4, 5}}
	)
	test.Test(cases, ser, t)
	test.TestSkip(cases, ser, t)
}

func TestLenArray(t *testing.T) {
	var (
		ser   = LenArrayMUS
		cases = []LenArray{{}, {1, 2, 3}, {4, 5, 6}}
	)
	test.Test(cases, ser, t)
	test.TestSkip(cases, ser, t)
}

func TestLenMap(t *testing.T) {
	var (
		ser   = LenMapMUS
		cases = []LenMap{{}, {"a": 1, "b": 2}}
	)
	test.Test(cases, ser, t)
	test.TestSkip(cases, ser, t)
}

func TestSlice(t *testing.T) {
	var (
		ser   = SliceMUS
		cases = []Slice{{}, {1, 2, 3}}
	)
	test.Test(cases, ser, t)
	test.TestSkip(cases, ser, t)
}

func TestArray(t *testing.T) {
	var (
		ser   = ArrayMUS
		cases = []Array{{}, {1, 2, 3}}
	)
	test.Test(cases, ser, t)
	test.TestSkip(cases, ser, t)
}

func TestMap(t *testing.T) {
	var (
		ser   = MapMUS
		cases = []Map{{}, {"foo": 1, "bar": 2}}
	)
	test.Test(cases, ser, t)
	test.TestSkip(cases, ser, t)
}

func TestPtr(t *testing.T) {
	var (
		v1    = 10
		ser   = PtrMUS
		cases = []Ptr{nil, &v1}
	)
	test.Test(cases, ser, t)
	test.TestSkip(cases, ser, t)
}

func TestValidString(t *testing.T) {
	var (
		ser   = ValidStringMUS
		cases = []ValidString{"hello", "world"}
	)
	test.Test(cases, ser, t)
	test.TestSkip(cases, ser, t)
}

func TestValidString_ValidateLen(t *testing.T) {
	var (
		ser      = ValidStringMUS
		testCase = ValidString("")
		wantErr  = ErrZeroLen
	)
	test.TestValidation(testCase, ser, wantErr, t)
}

func TestValidSlice(t *testing.T) {
	var (
		ser   = ValidSliceMUS
		cases = []ValidSlice{{1, 2, 3}, {4, 5}}
	)
	test.Test(cases, ser, t)
	test.TestSkip(cases, ser, t)
}

func TestValidSlice_ValidateLen(t *testing.T) {
	var (
		ser      = ValidSliceMUS
		testCase = ValidSlice{}
		wantErr  = ErrZeroLen
	)
	test.TestValidation(testCase, ser, wantErr, t)
}

func TestValidSlice_ValidateNum(t *testing.T) {
	var (
		ser      = ValidSliceMUS
		testCase = ValidSlice{-1}
		wantErr  = ErrNegativeNum
	)
	test.TestValidation(testCase, ser, wantErr, t)
}

func TestValidArray(t *testing.T) {
	var (
		ser   = ValidArrayMUS
		cases = []ValidArray{{1, 2, 3}, {4, 5, 0}}
	)
	test.Test(cases, ser, t)
	test.TestSkip(cases, ser, t)
}

func TestValidArray_ValidateNum(t *testing.T) {
	var (
		ser      = ValidArrayMUS
		testCase = ValidArray{-1, 0, 0}
		wantErr  = ErrNegativeNum
	)
	test.TestValidation(testCase, ser, wantErr, t)
}

func TestValidMap(t *testing.T) {
	var (
		ser   = ValidMapMUS
		cases = []ValidMap{{"a": 1, "b": 2}}
	)
	test.Test(cases, ser, t)
	test.TestSkip(cases, ser, t)
}

func TestValidMap_ValidateLen(t *testing.T) {
	var (
		ser      = ValidMapMUS
		testCase = ValidMap{}
		wantErr  = ErrZeroLen
	)
	test.TestValidation(testCase, ser, wantErr, t)
}

func TestValidMap_ValidateStr(t *testing.T) {
	var (
		ser      = ValidMapMUS
		testCase = ValidMap{"": 1}
		wantErr  = ErrEmptyStr
	)
	test.TestValidation(testCase, ser, wantErr, t)
}

func TestValidMap_ValidateNum(t *testing.T) {
	var (
		ser      = ValidMapMUS
		testCase = ValidMap{"a": -1}
		wantErr  = ErrNegativeNum
	)
	test.TestValidation(testCase, ser, wantErr, t)
}

func TestComplexMap(t *testing.T) {
	var (
		ser = ComplexMapMUS
		v1  = []int{1, 2}
		s   = ComplexMap{"a": {&v1: [][]float32{{1.1, 2.2}}}}
		bs  = make([]byte, ser.Size(s))
	)
	ser.Marshal(s, bs)
	v, n, err := ser.Unmarshal(bs)
	if err != nil {
		t.Fatal(err)
	}
	if n != len(bs) {
		t.Errorf("expected n %d, actual %d", len(bs), n)
	}

	// Manual comparison for map with pointer keys
	for k, m1 := range s {
		m2, ok := v[k]
		if !ok {
			t.Errorf("missing key %s", k)
			continue
		}
		if len(m1) != len(m2) {
			t.Errorf("lengths differ: expected %d, actual %d", len(m1), len(m2))
			continue
		}
		for k1, v1 := range m1 {
			found := false
			for k2, v2 := range m2 {
				if len(*k1) == len(*k2) {
					match := true
					for i := range *k1 {
						if (*k1)[i] != (*k2)[i] {
							match = false
							break
						}
					}
					if match {
						found = true
						if len(v1) != len(v2) || len(v1[0]) != len(v2[0]) || v1[0][0] != v2[0][0] {
							t.Errorf("values differ for key %v", k1)
						}
						break
					}
				}
			}
			if !found {
				t.Errorf("could not find key matching %v", k1)
			}
		}
	}
}
