// Code generated by AI agent with mus-skill. DO NOT EDIT.

package test

import (
	com "github.com/mus-format/common-go"
	arropts "github.com/mus-format/mus-go/options/array"
	mapopts "github.com/mus-format/mus-go/options/map"
	slopts "github.com/mus-format/mus-go/options/slice"
	stropts "github.com/mus-format/mus-go/options/string"
	"github.com/mus-format/mus-go/ord"
	"github.com/mus-format/mus-go/raw"
	"github.com/mus-format/mus-go/unsafe"
	"github.com/mus-format/mus-go/varint"
)

// Anonymous serializers
var (
	stringMF99ONdUftYWQQNRKtodPQΞΞ = ord.NewStringSer(stropts.WithLenSer(raw.Int))
	sliceTJ3WKpJc9DIP2ΔCTEOiRpQΞΞ  = ord.NewSliceSer(varint.Int, slopts.WithLenSer[int](raw.Int))
	arrayTJ3WKpJc9DIP2ΔCTEOiRpQΞΞ  = unsafe.NewArraySer[LenArray, int](varint.Int, arropts.WithLenSer[int](raw.Int))
	maptj7rE40BWy6Wa1YIqw5EvQΞΞ    = ord.NewMapSer(ord.String, varint.Int, mapopts.WithLenSer[string, int](raw.Int))
	sliceΔnFT9Δ0ctsD88vΔyΔsIXSAΞΞ  = ord.NewSliceSer(varint.Int)
	arrayΔnFT9Δ0ctsD88vΔyΔsIXSAΞΞ  = unsafe.NewArraySer[Array, int](varint.Int)
	mapvfMP8yFcgYs1TOfNVwi29wΞΞ    = ord.NewMapSer(ord.String, varint.Int)
	ptrΔnFT9Δ0ctsD88vΔyΔsIXSAΞΞ    = ord.NewPtrSer(varint.Int)
	stringsJHyAKL7nhY54WFOdFAUjQΞΞ = ord.NewValidStringSer(stropts.WithLenValidator(com.ValidatorFn[int](ValidateLen)))
	slicegkfΔjO3DapAΣHs6cyt7KRgΞΞ  = ord.NewValidSliceSer(varint.Int, slopts.WithLenValidator[int](com.ValidatorFn[int](ValidateLen)), slopts.WithElemValidator[int](com.ValidatorFn[int](ValidateNum)))
	array4DFYjpNi15cEjcVaMAxjTQΞΞ  = unsafe.NewValidArraySer[ValidArray, int](varint.Int, arropts.WithElemValidator[int](com.ValidatorFn[int](ValidateNum)))
	mapR87Hoh4ZXz8ZwyΣU9QSsDQΞΞ    = ord.NewValidMapSer(ord.String, varint.Int, mapopts.WithLenValidator[string, int](com.ValidatorFn[int](ValidateLen)), mapopts.WithKeyValidator[string, int](com.ValidatorFn[string](ValidateStr)), mapopts.WithValueValidator[string, int](com.ValidatorFn[int](ValidateNum)))

	ptrjmb5GxEBhCk0mIΣΔRJiRpAΞΞ   = ord.NewPtrSer(sliceΔnFT9Δ0ctsD88vΔyΔsIXSAΞΞ)
	slice0z7CsLvqbUcaRwbOoDDh4wΞΞ = ord.NewSliceSer(varint.Float32)
	slice8LΣTetutoyJtzn8soNUP5AΞΞ = ord.NewSliceSer(slice0z7CsLvqbUcaRwbOoDDh4wΞΞ)
	mapWvhJpLΔVMmar5pGflCu1RQΞΞ   = ord.NewMapSer(ptrjmb5GxEBhCk0mIΣΔRJiRpAΞΞ, slice8LΣTetutoyJtzn8soNUP5AΞΞ)
	mapKXBGv6hymjZΔBEx9MgqmrAΞΞ   = ord.NewValidMapSer(ord.String, mapWvhJpLΔVMmar5pGflCu1RQΞΞ, mapopts.WithLenValidator[string, map[*[]int][][]float32](com.ValidatorFn[int](ValidateLen)), mapopts.WithValueValidator[string, map[*[]int][][]float32](com.ValidatorFn[map[*[]int][][]float32](ValidateComplexMapValue)))
)

// LenStringMUS
var LenStringMUS = lenStringMUS{}

type lenStringMUS struct{}

func (s lenStringMUS) Marshal(v LenString, bs []byte) (n int) {
	return stringMF99ONdUftYWQQNRKtodPQΞΞ.Marshal(string(v), bs)
}
func (s lenStringMUS) Unmarshal(bs []byte) (v LenString, n int, err error) {
	tmp, n, err := stringMF99ONdUftYWQQNRKtodPQΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = LenString(tmp)
	return
}
func (s lenStringMUS) Size(v LenString) int { return stringMF99ONdUftYWQQNRKtodPQΞΞ.Size(string(v)) }
func (s lenStringMUS) Skip(bs []byte) (n int, err error) {
	return stringMF99ONdUftYWQQNRKtodPQΞΞ.Skip(bs)
}

// LenSliceMUS
var LenSliceMUS = lenSliceMUS{}

type lenSliceMUS struct{}

func (s lenSliceMUS) Marshal(v LenSlice, bs []byte) (n int) {
	return sliceTJ3WKpJc9DIP2ΔCTEOiRpQΞΞ.Marshal([]int(v), bs)
}
func (s lenSliceMUS) Unmarshal(bs []byte) (v LenSlice, n int, err error) {
	tmp, n, err := sliceTJ3WKpJc9DIP2ΔCTEOiRpQΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = LenSlice(tmp)
	return
}
func (s lenSliceMUS) Size(v LenSlice) int { return sliceTJ3WKpJc9DIP2ΔCTEOiRpQΞΞ.Size([]int(v)) }
func (s lenSliceMUS) Skip(bs []byte) (n int, err error) {
	return sliceTJ3WKpJc9DIP2ΔCTEOiRpQΞΞ.Skip(bs)
}

// LenArrayMUS
var LenArrayMUS = lenArrayMUS{}

type lenArrayMUS struct{}

func (s lenArrayMUS) Marshal(v LenArray, bs []byte) (n int) {
	return arrayTJ3WKpJc9DIP2ΔCTEOiRpQΞΞ.Marshal([3]int(v), bs)
}
func (s lenArrayMUS) Unmarshal(bs []byte) (v LenArray, n int, err error) {
	tmp, n, err := arrayTJ3WKpJc9DIP2ΔCTEOiRpQΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = LenArray(tmp)
	return
}
func (s lenArrayMUS) Size(v LenArray) int { return arrayTJ3WKpJc9DIP2ΔCTEOiRpQΞΞ.Size([3]int(v)) }
func (s lenArrayMUS) Skip(bs []byte) (n int, err error) {
	return arrayTJ3WKpJc9DIP2ΔCTEOiRpQΞΞ.Skip(bs)
}

// LenMapMUS
var LenMapMUS = lenMapMUS{}

type lenMapMUS struct{}

func (s lenMapMUS) Marshal(v LenMap, bs []byte) (n int) {
	return maptj7rE40BWy6Wa1YIqw5EvQΞΞ.Marshal(map[string]int(v), bs)
}
func (s lenMapMUS) Unmarshal(bs []byte) (v LenMap, n int, err error) {
	tmp, n, err := maptj7rE40BWy6Wa1YIqw5EvQΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = LenMap(tmp)
	return
}
func (s lenMapMUS) Size(v LenMap) int                 { return maptj7rE40BWy6Wa1YIqw5EvQΞΞ.Size(map[string]int(v)) }
func (s lenMapMUS) Skip(bs []byte) (n int, err error) { return maptj7rE40BWy6Wa1YIqw5EvQΞΞ.Skip(bs) }

// SliceMUS
var SliceMUS = sliceMUS{}

type sliceMUS struct{}

func (s sliceMUS) Marshal(v Slice, bs []byte) (n int) {
	return sliceΔnFT9Δ0ctsD88vΔyΔsIXSAΞΞ.Marshal([]int(v), bs)
}
func (s sliceMUS) Unmarshal(bs []byte) (v Slice, n int, err error) {
	tmp, n, err := sliceΔnFT9Δ0ctsD88vΔyΔsIXSAΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = Slice(tmp)
	return
}
func (s sliceMUS) Size(v Slice) int { return sliceΔnFT9Δ0ctsD88vΔyΔsIXSAΞΞ.Size([]int(v)) }
func (s sliceMUS) Skip(bs []byte) (n int, err error) {
	return sliceΔnFT9Δ0ctsD88vΔyΔsIXSAΞΞ.Skip(bs)
}

// ArrayMUS
var ArrayMUS = arrayMUS{}

type arrayMUS struct{}

func (s arrayMUS) Marshal(v Array, bs []byte) (n int) {
	return arrayΔnFT9Δ0ctsD88vΔyΔsIXSAΞΞ.Marshal([3]int(v), bs)
}
func (s arrayMUS) Unmarshal(bs []byte) (v Array, n int, err error) {
	tmp, n, err := arrayΔnFT9Δ0ctsD88vΔyΔsIXSAΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = Array(tmp)
	return
}
func (s arrayMUS) Size(v Array) int { return arrayΔnFT9Δ0ctsD88vΔyΔsIXSAΞΞ.Size([3]int(v)) }
func (s arrayMUS) Skip(bs []byte) (n int, err error) {
	return arrayΔnFT9Δ0ctsD88vΔyΔsIXSAΞΞ.Skip(bs)
}

// MapMUS
var MapMUS = mapMUS{}

type mapMUS struct{}

func (s mapMUS) Marshal(v Map, bs []byte) (n int) {
	return mapvfMP8yFcgYs1TOfNVwi29wΞΞ.Marshal(map[string]int(v), bs)
}
func (s mapMUS) Unmarshal(bs []byte) (v Map, n int, err error) {
	tmp, n, err := mapvfMP8yFcgYs1TOfNVwi29wΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = Map(tmp)
	return
}
func (s mapMUS) Size(v Map) int                    { return mapvfMP8yFcgYs1TOfNVwi29wΞΞ.Size(map[string]int(v)) }
func (s mapMUS) Skip(bs []byte) (n int, err error) { return mapvfMP8yFcgYs1TOfNVwi29wΞΞ.Skip(bs) }

// PtrMUS
var PtrMUS = ptrMUS{}

type ptrMUS struct{}

func (s ptrMUS) Marshal(v Ptr, bs []byte) (n int) {
	return ptrΔnFT9Δ0ctsD88vΔyΔsIXSAΞΞ.Marshal((*int)(v), bs)
}
func (s ptrMUS) Unmarshal(bs []byte) (v Ptr, n int, err error) {
	tmp, n, err := ptrΔnFT9Δ0ctsD88vΔyΔsIXSAΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = Ptr(tmp)
	return
}
func (s ptrMUS) Size(v Ptr) int                    { return ptrΔnFT9Δ0ctsD88vΔyΔsIXSAΞΞ.Size((*int)(v)) }
func (s ptrMUS) Skip(bs []byte) (n int, err error) { return ptrΔnFT9Δ0ctsD88vΔyΔsIXSAΞΞ.Skip(bs) }

// ValidStringMUS
var ValidStringMUS = validStringMUS{}

type validStringMUS struct{}

func (s validStringMUS) Marshal(v ValidString, bs []byte) (n int) {
	return stringsJHyAKL7nhY54WFOdFAUjQΞΞ.Marshal(string(v), bs)
}
func (s validStringMUS) Unmarshal(bs []byte) (v ValidString, n int, err error) {
	tmp, n, err := stringsJHyAKL7nhY54WFOdFAUjQΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = ValidString(tmp)
	return
}
func (s validStringMUS) Size(v ValidString) int {
	return stringsJHyAKL7nhY54WFOdFAUjQΞΞ.Size(string(v))
}
func (s validStringMUS) Skip(bs []byte) (n int, err error) {
	return stringsJHyAKL7nhY54WFOdFAUjQΞΞ.Skip(bs)
}

// ValidSliceMUS
var ValidSliceMUS = validSliceMUS{}

type validSliceMUS struct{}

func (s validSliceMUS) Marshal(v ValidSlice, bs []byte) (n int) {
	return slicegkfΔjO3DapAΣHs6cyt7KRgΞΞ.Marshal([]int(v), bs)
}
func (s validSliceMUS) Unmarshal(bs []byte) (v ValidSlice, n int, err error) {
	tmp, n, err := slicegkfΔjO3DapAΣHs6cyt7KRgΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = ValidSlice(tmp)
	return
}
func (s validSliceMUS) Size(v ValidSlice) int {
	return slicegkfΔjO3DapAΣHs6cyt7KRgΞΞ.Size([]int(v))
}
func (s validSliceMUS) Skip(bs []byte) (n int, err error) {
	return slicegkfΔjO3DapAΣHs6cyt7KRgΞΞ.Skip(bs)
}

// ValidArrayMUS
var ValidArrayMUS = validArrayMUS{}

type validArrayMUS struct{}

func (s validArrayMUS) Marshal(v ValidArray, bs []byte) (n int) {
	return array4DFYjpNi15cEjcVaMAxjTQΞΞ.Marshal([3]int(v), bs)
}
func (s validArrayMUS) Unmarshal(bs []byte) (v ValidArray, n int, err error) {
	tmp, n, err := array4DFYjpNi15cEjcVaMAxjTQΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = ValidArray(tmp)
	return
}
func (s validArrayMUS) Size(v ValidArray) int { return array4DFYjpNi15cEjcVaMAxjTQΞΞ.Size([3]int(v)) }
func (s validArrayMUS) Skip(bs []byte) (n int, err error) {
	return array4DFYjpNi15cEjcVaMAxjTQΞΞ.Skip(bs)
}

// ValidMapMUS
var ValidMapMUS = validMapMUS{}

type validMapMUS struct{}

func (s validMapMUS) Marshal(v ValidMap, bs []byte) (n int) {
	return mapR87Hoh4ZXz8ZwyΣU9QSsDQΞΞ.Marshal(map[string]int(v), bs)
}
func (s validMapMUS) Unmarshal(bs []byte) (v ValidMap, n int, err error) {
	tmp, n, err := mapR87Hoh4ZXz8ZwyΣU9QSsDQΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = ValidMap(tmp)
	return
}
func (s validMapMUS) Size(v ValidMap) int {
	return mapR87Hoh4ZXz8ZwyΣU9QSsDQΞΞ.Size(map[string]int(v))
}
func (s validMapMUS) Skip(bs []byte) (n int, err error) {
	return mapR87Hoh4ZXz8ZwyΣU9QSsDQΞΞ.Skip(bs)
}

// ComplexMapMUS
var ComplexMapMUS = complexMapMUS{}

type complexMapMUS struct{}

func (s complexMapMUS) Marshal(v ComplexMap, bs []byte) (n int) {
	return mapKXBGv6hymjZΔBEx9MgqmrAΞΞ.Marshal(map[string]map[*[]int][][]float32(v), bs)
}
func (s complexMapMUS) Unmarshal(bs []byte) (v ComplexMap, n int, err error) {
	tmp, n, err := mapKXBGv6hymjZΔBEx9MgqmrAΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = ComplexMap(tmp)
	return
}
func (s complexMapMUS) Size(v ComplexMap) int {
	return mapKXBGv6hymjZΔBEx9MgqmrAΞΞ.Size(map[string]map[*[]int][][]float32(v))
}
func (s complexMapMUS) Skip(bs []byte) (n int, err error) {
	return mapKXBGv6hymjZΔBEx9MgqmrAΞΞ.Skip(bs)
}
