// Code generated by AI agent with mus-skill. DO NOT EDIT.

package test

import (
	"github.com/mus-format/mus-go/raw"
	"github.com/mus-format/mus-go/varint"
)

// IntMUS
var IntMUS = intMUS{}

type intMUS struct{}

func (s intMUS) Marshal(v Int, bs []byte) (n int) {
	return varint.Int.Marshal(int(v), bs)
}

func (s intMUS) Unmarshal(bs []byte) (v Int, n int, err error) {
	tmp, n, err := varint.Int.Unmarshal(bs)
	if err != nil {
		return
	}
	v = Int(tmp)
	return
}

func (s intMUS) Size(v Int) (size int) {
	return varint.Int.Size(int(v))
}

func (s intMUS) Skip(bs []byte) (n int, err error) {
	return varint.Int.Skip(bs)
}

// RawIntMUS
var RawIntMUS = rawIntMUS{}

type rawIntMUS struct{}

func (s rawIntMUS) Marshal(v RawInt, bs []byte) (n int) {
	return raw.Int.Marshal(int(v), bs)
}

func (s rawIntMUS) Unmarshal(bs []byte) (v RawInt, n int, err error) {
	tmp, n, err := raw.Int.Unmarshal(bs)
	if err != nil {
		return
	}
	v = RawInt(tmp)
	return
}

func (s rawIntMUS) Size(v RawInt) (size int) {
	return raw.Int.Size(int(v))
}

func (s rawIntMUS) Skip(bs []byte) (n int, err error) {
	return raw.Int.Skip(bs)
}

// ValidIntMUS
var ValidIntMUS = validIntMUS{}

type validIntMUS struct{}

func (s validIntMUS) Marshal(v ValidInt, bs []byte) (n int) {
	return varint.Int.Marshal(int(v), bs)
}

func (s validIntMUS) Unmarshal(bs []byte) (v ValidInt, n int, err error) {
	tmp, n, err := varint.Int.Unmarshal(bs)
	if err != nil {
		return
	}
	v = ValidInt(tmp)
	if err = ValidateInt(v); err != nil {
		return
	}
	return
}

func (s validIntMUS) Size(v ValidInt) (size int) {
	return varint.Int.Size(int(v))
}

func (s validIntMUS) Skip(bs []byte) (n int, err error) {
	return varint.Int.Skip(bs)
}
