// Code generated by AI agent with mus-skill. DO NOT EDIT.

package test

import (
	"testing"

	"github.com/mus-format/mus-go/test"
)

func TestInt(t *testing.T) {
	var (
		ser   = IntMUS
		cases = []Int{0, 1, -1, 100, -100}
	)
	test.Test(cases, ser, t)
	test.TestSkip(cases, ser, t)
}

func TestRawInt(t *testing.T) {
	var (
		ser   = RawIntMUS
		cases = []RawInt{0, 1, -1, 100, -100}
	)
	test.Test(cases, ser, t)
	test.TestSkip(cases, ser, t)
}

func TestValidInt(t *testing.T) {
	var (
		ser   = ValidIntMUS
		cases = []ValidInt{0, 1, 100}
	)
	test.Test(cases, ser, t)
	test.TestSkip(cases, ser, t)
}

func TestValidInt_ValidateNum(t *testing.T) {
	var (
		ser      = ValidIntMUS
		testCase = ValidInt(-1)
		wantErr  = ErrNegativeNum
	)
	test.TestValidation(testCase, ser, wantErr, t)
}
