// Code generated by AI agent with mus-skill. DO NOT EDIT.

package test

import (
	"testing"

	"github.com/mus-format/mus-go/test"
)

func TestInterface(t *testing.T) {
	var (
		ser   = InterfaceMUS
		cases = []Interface{
			Impl1{Num: 1},
			Impl2("hello"),
		}
	)
	test.Test(cases, ser, t)
	test.TestSkip(cases, ser, t)
}

func TestMarshallerInterface(t *testing.T) {
	var (
		ser   = MarshallerInterfaceMUS
		cases = []MarshallerInterface{
			Impl1{Num: 2},
			Impl2("world"),
		}
	)
	test.Test(cases, ser, t)
	test.TestSkip(cases, ser, t)
}
