// Code generated by AI agent with mus-skill. DO NOT EDIT.

package test

import (
	"fmt"
	"reflect"

	com "github.com/mus-format/common-go"
	"github.com/mus-format/mus-go"
	"github.com/mus-format/mus-go/ord"
	"github.com/mus-format/mus-go/typed"
	"github.com/mus-format/mus-go/varint"
)

// Impl1MUS
var Impl1MUS = impl1MUS{}

type impl1MUS struct{}

func (s impl1MUS) Marshal(v Impl1, bs []byte) (n int) {
	return varint.Int.Marshal(v.Num, bs)
}

func (s impl1MUS) Unmarshal(bs []byte) (v Impl1, n int, err error) {
	v.Num, n, err = varint.Int.Unmarshal(bs)
	return
}

func (s impl1MUS) Size(v Impl1) (size int) {
	return varint.Int.Size(v.Num)
}

func (s impl1MUS) Skip(bs []byte) (n int, err error) {
	return varint.Int.Skip(bs)
}

// Impl2MUS
var Impl2MUS = impl2MUS{}

type impl2MUS struct{}

func (s impl2MUS) Marshal(v Impl2, bs []byte) (n int) {
	return ord.String.Marshal(string(v), bs)
}

func (s impl2MUS) Unmarshal(bs []byte) (v Impl2, n int, err error) {
	tmp, n, err := ord.String.Unmarshal(bs)
	if err != nil {
		return
	}
	v = Impl2(tmp)
	return
}

func (s impl2MUS) Size(v Impl2) (size int) {
	return ord.String.Size(string(v))
}

func (s impl2MUS) Skip(bs []byte) (n int, err error) {
	return ord.String.Skip(bs)
}

// Typed serializers
var (
	Impl1TypedMUS = typed.NewSer(Impl1DTM, Impl1MUS)
	Impl2TypedMUS = typed.NewSer(Impl2DTM, Impl2MUS)
)

// InterfaceMUS
var InterfaceMUS = interfaceMUS{}

type interfaceMUS struct{}

func (s interfaceMUS) Marshal(v Interface, bs []byte) (n int) {
	switch val := v.(type) {
	case Impl1:
		return Impl1TypedMUS.Marshal(val, bs)
	case Impl2:
		return Impl2TypedMUS.Marshal(val, bs)
	default:
		panic(fmt.Sprintf(com.ErrorPrefix+"unexpected %v type", v))
	}
}

func (s interfaceMUS) Unmarshal(bs []byte) (v Interface, n int, err error) {
	dtm, n, err := typed.DTMSer.Unmarshal(bs)
	if err != nil {
		return
	}
	switch dtm {
	case Impl1DTM:
		var tmp Impl1
		var n1 int
		tmp, n1, err = Impl1TypedMUS.UnmarshalData(bs[n:])
		if err != nil {
			return
		}
		v = tmp
		n += n1
	case Impl2DTM:
		var tmp Impl2
		var n1 int
		tmp, n1, err = Impl2TypedMUS.UnmarshalData(bs[n:])
		if err != nil {
			return
		}
		v = tmp
		n += n1
	default:
		err = com.NewUnexpectedDTMError(dtm)
		return
	}
	return
}

func (s interfaceMUS) Size(v Interface) (size int) {
	switch val := v.(type) {
	case Impl1:
		return Impl1TypedMUS.Size(val)
	case Impl2:
		return Impl2TypedMUS.Size(val)
	default:
		panic(fmt.Sprintf(com.ErrorPrefix+"unexpected %v type", v))
	}
}

func (s interfaceMUS) Skip(bs []byte) (n int, err error) {
	dtm, n, err := typed.DTMSer.Unmarshal(bs)
	if err != nil {
		return
	}
	var n1 int
	switch dtm {
	case Impl1DTM:
		n1, err = Impl1TypedMUS.SkipData(bs[n:])
	case Impl2DTM:
		n1, err = Impl2TypedMUS.SkipData(bs[n:])
	default:
		err = com.NewUnexpectedDTMError(dtm)
		return
	}
	n += n1
	return
}

// MarshallerInterfaceMUS
var MarshallerInterfaceMUS = marshallerInterfaceMUS{}

type marshallerInterfaceMUS struct{}

func (s marshallerInterfaceMUS) Marshal(v MarshallerInterface, bs []byte) (n int) {
	if m, ok := v.(mus.MarshallerTyped); ok {
		return m.MarshalTypedMUS(bs)
	}
	panic(fmt.Sprintf("%v doesn't implement the mus.MarshallerTyped interface", reflect.TypeOf(v)))
}

func (s marshallerInterfaceMUS) Unmarshal(bs []byte) (v MarshallerInterface, n int, err error) {
	dtm, n, err := typed.DTMSer.Unmarshal(bs)
	if err != nil {
		return
	}
	switch dtm {
	case Impl1DTM:
		var tmp Impl1
		var n1 int
		tmp, n1, err = Impl1TypedMUS.UnmarshalData(bs[n:])
		if err != nil {
			return
		}
		v = tmp
		n += n1
	case Impl2DTM:
		var tmp Impl2
		var n1 int
		tmp, n1, err = Impl2TypedMUS.UnmarshalData(bs[n:])
		if err != nil {
			return
		}
		v = tmp
		n += n1
	default:
		err = com.NewUnexpectedDTMError(dtm)
		return
	}
	return
}

func (s marshallerInterfaceMUS) Size(v MarshallerInterface) (size int) {
	if m, ok := v.(mus.MarshallerTyped); ok {
		return m.SizeTypedMUS()
	}
	panic(fmt.Sprintf("%v doesn't implement the mus.MarshallerTyped interface", reflect.TypeOf(v)))
}

func (s marshallerInterfaceMUS) Skip(bs []byte) (n int, err error) {
	dtm, n, err := typed.DTMSer.Unmarshal(bs)
	if err != nil {
		return
	}
	var n1 int
	switch dtm {
	case Impl1DTM:
		n1, err = Impl1TypedMUS.SkipData(bs[n:])
	case Impl2DTM:
		n1, err = Impl2TypedMUS.SkipData(bs[n:])
	default:
		err = com.NewUnexpectedDTMError(dtm)
		return
	}
	n += n1
	return
}
