// Code generated by AI agent with mus-skill. DO NOT EDIT.

package test

import (
	"fmt"
	"reflect"

	com "github.com/mus-format/common-go"
	"github.com/mus-format/mus-go"
	"github.com/mus-format/mus-go/ord"
	"github.com/mus-format/mus-go/typed"
	"github.com/mus-format/mus-go/varint"
)

// DTM constants
const (
	Impl3DTM com.DTM = iota + 1
	Impl4DTM
	Impl5DTM
	Impl6DTM
)

// Impl3MUS
var Impl3MUS = impl3MUS{}

type impl3MUS struct{}

func (s impl3MUS) Marshal(v Impl3, bs []byte) (n int) {
	return varint.Int.Marshal(v.Num, bs)
}

func (s impl3MUS) Unmarshal(bs []byte) (v Impl3, n int, err error) {
	v.Num, n, err = varint.Int.Unmarshal(bs)
	return
}

func (s impl3MUS) Size(v Impl3) (size int) {
	return varint.Int.Size(v.Num)
}

func (s impl3MUS) Skip(bs []byte) (n int, err error) {
	return varint.Int.Skip(bs)
}

// Impl4MUS
var Impl4MUS = impl4MUS{}

type impl4MUS struct{}

func (s impl4MUS) Marshal(v Impl4, bs []byte) (n int) {
	return ord.String.Marshal(string(v), bs)
}

func (s impl4MUS) Unmarshal(bs []byte) (v Impl4, n int, err error) {
	tmp, n, err := ord.String.Unmarshal(bs)
	if err != nil {
		return
	}
	v = Impl4(tmp)
	return
}

func (s impl4MUS) Size(v Impl4) (size int) {
	return ord.String.Size(string(v))
}

func (s impl4MUS) Skip(bs []byte) (n int, err error) {
	return ord.String.Skip(bs)
}

// Impl5MUS
var Impl5MUS = impl5MUS{}

type impl5MUS struct{}

func (s impl5MUS) Marshal(v Impl5, bs []byte) (n int) {
	return varint.Int.Marshal(v.Num, bs)
}

func (s impl5MUS) Unmarshal(bs []byte) (v Impl5, n int, err error) {
	v.Num, n, err = varint.Int.Unmarshal(bs)
	return
}

func (s impl5MUS) Size(v Impl5) (size int) {
	return varint.Int.Size(v.Num)
}

func (s impl5MUS) Skip(bs []byte) (n int, err error) {
	return varint.Int.Skip(bs)
}

// Impl6MUS
var Impl6MUS = impl6MUS{}

type impl6MUS struct{}

func (s impl6MUS) Marshal(v Impl6, bs []byte) (n int) {
	return ord.String.Marshal(string(v), bs)
}

func (s impl6MUS) Unmarshal(bs []byte) (v Impl6, n int, err error) {
	tmp, n, err := ord.String.Unmarshal(bs)
	if err != nil {
		return
	}
	v = Impl6(tmp)
	return
}

func (s impl6MUS) Size(v Impl6) (size int) {
	return ord.String.Size(string(v))
}

func (s impl6MUS) Skip(bs []byte) (n int, err error) {
	return ord.String.Skip(bs)
}

// Typed serializers
var (
	Impl3TypedMUS = typed.NewTypedSer(Impl3DTM, Impl3MUS)
	Impl4TypedMUS = typed.NewTypedSer(Impl4DTM, Impl4MUS)
	Impl5TypedMUS = typed.NewTypedSer(Impl5DTM, Impl5MUS)
	Impl6TypedMUS = typed.NewTypedSer(Impl6DTM, Impl6MUS)
)

// InterfaceRegisterMUS
var InterfaceRegisterMUS = interfaceRegisterMUS{}

type interfaceRegisterMUS struct{}

func (s interfaceRegisterMUS) Marshal(v InterfaceRegister, bs []byte) (n int) {
	switch val := v.(type) {
	case Impl3:
		return Impl3TypedMUS.Marshal(val, bs)
	case Impl4:
		return Impl4TypedMUS.Marshal(val, bs)
	default:
		panic(fmt.Sprintf(com.ErrorPrefix+"unexpected %v type", v))
	}
}

func (s interfaceRegisterMUS) Unmarshal(bs []byte) (v InterfaceRegister, n int, err error) {
	dtm, n, err := typed.DTMSer.Unmarshal(bs)
	if err != nil {
		return
	}
	switch dtm {
	case Impl3DTM:
		var tmp Impl3
		var n1 int
		tmp, n1, err = Impl3TypedMUS.UnmarshalData(bs[n:])
		if err != nil {
			return
		}
		v = tmp
		n += n1
	case Impl4DTM:
		var tmp Impl4
		var n1 int
		tmp, n1, err = Impl4TypedMUS.UnmarshalData(bs[n:])
		if err != nil {
			return
		}
		v = tmp
		n += n1
	default:
		err = com.NewUnexpectedDTMError(dtm)
		return
	}
	return
}

func (s interfaceRegisterMUS) Size(v InterfaceRegister) (size int) {
	switch val := v.(type) {
	case Impl3:
		return Impl3TypedMUS.Size(val)
	case Impl4:
		return Impl4TypedMUS.Size(val)
	default:
		panic(fmt.Sprintf(com.ErrorPrefix+"unexpected %v type", v))
	}
}

func (s interfaceRegisterMUS) Skip(bs []byte) (n int, err error) {
	dtm, n, err := typed.DTMSer.Unmarshal(bs)
	if err != nil {
		return
	}
	var n1 int
	switch dtm {
	case Impl3DTM:
		n1, err = Impl3TypedMUS.SkipData(bs[n:])
	case Impl4DTM:
		n1, err = Impl4TypedMUS.SkipData(bs[n:])
	default:
		err = com.NewUnexpectedDTMError(dtm)
		return
	}
	n += n1
	return
}

// MarshallerInterfaceRegisterMUS
var MarshallerInterfaceRegisterMUS = marshallerInterfaceRegisterMUS{}

type marshallerInterfaceRegisterMUS struct{}

func (s marshallerInterfaceRegisterMUS) Marshal(v MarshallerInterfaceRegister, bs []byte) (n int) {
	if m, ok := v.(mus.MarshallerTyped); ok {
		return m.MarshalTypedMUS(bs)
	}
	panic(fmt.Sprintf("%v doesn't implement the mus.MarshallerTyped interface", reflect.TypeOf(v)))
}

func (s marshallerInterfaceRegisterMUS) Unmarshal(bs []byte) (v MarshallerInterfaceRegister, n int, err error) {
	dtm, n, err := typed.DTMSer.Unmarshal(bs)
	if err != nil {
		return
	}
	switch dtm {
	case Impl5DTM:
		var tmp Impl5
		var n1 int
		tmp, n1, err = Impl5TypedMUS.UnmarshalData(bs[n:])
		if err != nil {
			return
		}
		v = tmp
		n += n1
	case Impl6DTM:
		var tmp Impl6
		var n1 int
		tmp, n1, err = Impl6TypedMUS.UnmarshalData(bs[n:])
		if err != nil {
			return
		}
		v = tmp
		n += n1
	default:
		err = com.NewUnexpectedDTMError(dtm)
		return
	}
	return
}

func (s marshallerInterfaceRegisterMUS) Size(v MarshallerInterfaceRegister) (size int) {
	if m, ok := v.(mus.MarshallerTyped); ok {
		return m.SizeTypedMUS()
	}
	panic(fmt.Sprintf("%v doesn't implement the mus.MarshallerTyped interface", reflect.TypeOf(v)))
}

func (s marshallerInterfaceRegisterMUS) Skip(bs []byte) (n int, err error) {
	dtm, n, err := typed.DTMSer.Unmarshal(bs)
	if err != nil {
		return
	}
	var n1 int
	switch dtm {
	case Impl5DTM:
		n1, err = Impl5TypedMUS.SkipData(bs[n:])
	case Impl6DTM:
		n1, err = Impl6TypedMUS.SkipData(bs[n:])
	default:
		err = com.NewUnexpectedDTMError(dtm)
		return
	}
	n += n1
	return
}
