// Code generated by AI agent with mus-skill. DO NOT EDIT.

package test

import (
	"testing"

	"github.com/mus-format/mus-go/test"
)

func TestInterfaceRegister(t *testing.T) {
	var (
		ser   = InterfaceRegisterMUS
		cases = []InterfaceRegister{
			Impl3{Num: 3},
			Impl4("hi"),
		}
	)
	test.Test(cases, ser, t)
	test.TestSkip(cases, ser, t)
}

func TestMarshallerInterfaceRegister(t *testing.T) {
	var (
		ser   = MarshallerInterfaceRegisterMUS
		cases = []MarshallerInterfaceRegister{
			Impl5{Num: 5},
			Impl6("bye"),
		}
	)
	test.Test(cases, ser, t)
	test.TestSkip(cases, ser, t)
}
