// Code generated by AI agent with mus-skill. DO NOT EDIT.

package test

import (
	"time"

	"github.com/mus-format/mus-go/ord"
	"github.com/mus-format/mus-go/raw"
	"github.com/mus-format/mus-go/varint"
)

// SimpleStructMUS
var SimpleStructMUS = simpleStructMUS{}

type simpleStructMUS struct{}

func (s simpleStructMUS) Marshal(v SimpleStruct, bs []byte) (n int) {
	n = varint.Int.Marshal(v.Num, bs)
	return n + ord.String.Marshal(v.Str, bs[n:])
}

func (s simpleStructMUS) Unmarshal(bs []byte) (v SimpleStruct, n int, err error) {
	v.Num, n, err = varint.Int.Unmarshal(bs)
	if err != nil {
		return
	}
	var n1 int
	v.Str, n1, err = ord.String.Unmarshal(bs[n:])
	n += n1
	return
}

func (s simpleStructMUS) Size(v SimpleStruct) (size int) {
	size = varint.Int.Size(v.Num)
	return size + ord.String.Size(v.Str)
}

func (s simpleStructMUS) Skip(bs []byte) (n int, err error) {
	n, err = varint.Int.Skip(bs)
	if err != nil {
		return
	}
	var n1 int
	n1, err = ord.String.Skip(bs[n:])
	n += n1
	return
}

// IgnoreStructMUS
var IgnoreStructMUS = ignoreStructMUS{}

type ignoreStructMUS struct{}

func (s ignoreStructMUS) Marshal(v IgnoreStruct, bs []byte) (n int) {
	return varint.Int.Marshal(v.Num, bs)
}

func (s ignoreStructMUS) Unmarshal(bs []byte) (v IgnoreStruct, n int, err error) {
	v.Num, n, err = varint.Int.Unmarshal(bs)
	return
}

func (s ignoreStructMUS) Size(v IgnoreStruct) (size int) {
	return varint.Int.Size(v.Num)
}

func (s ignoreStructMUS) Skip(bs []byte) (n int, err error) {
	return varint.Int.Skip(bs)
}

// TimeStructMUS
var TimeStructMUS = timeStructMUS{}

type timeStructMUS struct{}

func (s timeStructMUS) Marshal(v TimeStruct, bs []byte) (n int) {
	return raw.TimeUnix.Marshal(time.Time(v), bs)
}

func (s timeStructMUS) Unmarshal(bs []byte) (v TimeStruct, n int, err error) {
	tmp, n, err := raw.TimeUnix.Unmarshal(bs)
	if err != nil {
		return
	}
	v = TimeStruct(tmp)
	return
}

func (s timeStructMUS) Size(v TimeStruct) (size int) {
	return raw.TimeUnix.Size(time.Time(v))
}

func (s timeStructMUS) Skip(bs []byte) (n int, err error) {
	return raw.TimeUnix.Skip(bs)
}

// InnerStructMUS
var InnerStructMUS = innerStructMUS{}

type innerStructMUS struct{}

func (s innerStructMUS) Marshal(v InnerStruct, bs []byte) (n int) {
	return ord.String.Marshal(v.Str, bs)
}

func (s innerStructMUS) Unmarshal(bs []byte) (v InnerStruct, n int, err error) {
	v.Str, n, err = ord.String.Unmarshal(bs)
	return
}

func (s innerStructMUS) Size(v InnerStruct) (size int) {
	return ord.String.Size(v.Str)
}

func (s innerStructMUS) Skip(bs []byte) (n int, err error) {
	return ord.String.Skip(bs)
}

// EmbeddingStructMUS
var EmbeddingStructMUS = embeddingStructMUS{}

type embeddingStructMUS struct{}

func (s embeddingStructMUS) Marshal(v EmbeddingStruct, bs []byte) (n int) {
	n = varint.Int.Marshal(v.Num, bs)
	return n + InnerStructMUS.Marshal(v.InnerStruct, bs[n:])
}

func (s embeddingStructMUS) Unmarshal(bs []byte) (v EmbeddingStruct, n int, err error) {
	v.Num, n, err = varint.Int.Unmarshal(bs)
	if err != nil {
		return
	}
	var n1 int
	v.InnerStruct, n1, err = InnerStructMUS.Unmarshal(bs[n:])
	n += n1
	return
}

func (s embeddingStructMUS) Size(v EmbeddingStruct) (size int) {
	size = varint.Int.Size(v.Num)
	return size + InnerStructMUS.Size(v.InnerStruct)
}

func (s embeddingStructMUS) Skip(bs []byte) (n int, err error) {
	n, err = varint.Int.Skip(bs)
	if err != nil {
		return
	}
	var n1 int
	n1, err = InnerStructMUS.Skip(bs[n:])
	n += n1
	return
}

// ValidStructMUS
var ValidStructMUS = validStructMUS{}

type validStructMUS struct{}

func (s validStructMUS) Marshal(v ValidStruct, bs []byte) (n int) {
	n = varint.Int.Marshal(v.Num, bs)
	return n + ord.String.Marshal(v.Str, bs[n:])
}

func (s validStructMUS) Unmarshal(bs []byte) (v ValidStruct, n int, err error) {
	v.Num, n, err = varint.Int.Unmarshal(bs)
	if err != nil {
		return
	}
	if err = ValidateNum(v.Num); err != nil {
		return
	}
	var n1 int
	v.Str, n1, err = ord.String.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	if err = ValidateStr(v.Str); err != nil {
		return
	}
	if err = ValidateStruct(v); err != nil {
		return
	}
	return
}

func (s validStructMUS) Size(v ValidStruct) (size int) {
	size = varint.Int.Size(v.Num)
	return size + ord.String.Size(v.Str)
}

func (s validStructMUS) Skip(bs []byte) (n int, err error) {
	n, err = varint.Int.Skip(bs)
	if err != nil {
		return
	}
	var n1 int
	n1, err = ord.String.Skip(bs[n:])
	n += n1
	return
}
