// Code generated by AI agent with mus-skill. DO NOT EDIT.

package test

import (
	"testing"
	"time"

	"github.com/mus-format/mus-go/test"
)

func TestSimpleStruct(t *testing.T) {
	var (
		ser   = SimpleStructMUS
		cases = []SimpleStruct{
			{Num: 1, Str: "hello"},
			{Num: -1, Str: ""},
		}
	)
	test.Test(cases, ser, t)
	test.TestSkip(cases, ser, t)
}

func TestIgnoreStruct(t *testing.T) {
	var (
		ser   = IgnoreStructMUS
		cases = []IgnoreStruct{
			{Num: 1},
			{Num: -1},
		}
	)
	test.Test(cases, ser, t)
	test.TestSkip(cases, ser, t)
}

func TestTimeStruct(t *testing.T) {
	var (
		ser   = TimeStructMUS
		cases = []TimeStruct{
			TimeStruct(time.Now().Truncate(time.Second)),
			TimeStruct(time.Unix(0, 0)),
		}
	)
	test.Test(cases, ser, t)
	test.TestSkip(cases, ser, t)
}

func TestInnerStruct(t *testing.T) {
	var (
		ser   = InnerStructMUS
		cases = []InnerStruct{
			{Str: "inner"},
			{Str: ""},
		}
	)
	test.Test(cases, ser, t)
	test.TestSkip(cases, ser, t)
}

func TestEmbeddingStruct(t *testing.T) {
	var (
		ser   = EmbeddingStructMUS
		cases = []EmbeddingStruct{
			{Num: 1, InnerStruct: InnerStruct{Str: "embedded"}},
			{Num: -1, InnerStruct: InnerStruct{Str: ""}},
		}
	)
	test.Test(cases, ser, t)
	test.TestSkip(cases, ser, t)
}

func TestValidStruct(t *testing.T) {
	var (
		ser   = ValidStructMUS
		cases = []ValidStruct{
			{Num: 1, Str: "valid"},
		}
	)
	test.Test(cases, ser, t)
	test.TestSkip(cases, ser, t)
}

func TestValidStruct_ValidateNum(t *testing.T) {
	var (
		ser      = ValidStructMUS
		testCase = ValidStruct{Num: -1, Str: "valid"}
		wantErr  = ErrNegativeNum
	)
	test.TestValidation(testCase, ser, wantErr, t)
}

func TestValidStruct_ValidateStr(t *testing.T) {
	var (
		ser      = ValidStructMUS
		testCase = ValidStruct{Num: 1, Str: ""}
		wantErr  = ErrEmptyStr
	)
	test.TestValidation(testCase, ser, wantErr, t)
}

func TestValidStruct_ValidateStruct(t *testing.T) {
	var (
		ser      = ValidStructMUS
		testCase = ValidStruct{Num: 10, Str: "hello"}
		wantErr  = ErrNotValidStruct
	)
	test.TestValidation(testCase, ser, wantErr, t)
}
