// Code generated by AI agent with mus-skill. DO NOT EDIT.

package test

import (
	"github.com/mus-format/mus-go/typed"
	"github.com/mus-format/mus-go/varint"
)

// TypedIntMUS
var TypedIntMUS = typedIntMUS{}

type typedIntMUS struct{}

func (s typedIntMUS) Marshal(v TypedInt, bs []byte) (n int) {
	return varint.Int.Marshal(int(v), bs)
}

func (s typedIntMUS) Unmarshal(bs []byte) (v TypedInt, n int, err error) {
	tmp, n, err := varint.Int.Unmarshal(bs)
	if err != nil {
		return
	}
	v = TypedInt(tmp)
	return
}

func (s typedIntMUS) Size(v TypedInt) (size int) {
	return varint.Int.Size(int(v))
}

func (s typedIntMUS) Skip(bs []byte) (n int, err error) {
	return varint.Int.Skip(bs)
}

// Typed serializers
var TypedIntTypedMUS = typed.NewTypedSer(TypedIntDTM, TypedIntMUS)
