// Code generated by AI agent with mus-skill. DO NOT EDIT.

package test

import (
	"testing"

	"github.com/mus-format/mus-go/test"
)

func TestTypedInt(t *testing.T) {
	var (
		ser   = TypedIntMUS
		cases = []TypedInt{0, 1, -1, 100, -100}
	)
	test.Test(cases, ser, t)
	test.TestSkip(cases, ser, t)
}

func TestTypedIntTyped(t *testing.T) {
	var (
		ser   = TypedIntTypedMUS
		cases = []TypedInt{0, 1, -1, 100, -100}
	)
	test.Test(cases, ser, t)
	test.TestSkip(cases, ser, t)
}
