// Code generated by the AI agent with mus-gen-skill-go. DO NOT EDIT.

package custommode

import (
	"testing"

	"github.com/mus-format/mus-stream-go/test"
)

func TestFoo(t *testing.T) {
	cases := []Foo{
		{num: 1, str: "custom"},
		{num: -1, str: ""},
	}
	test.Test(cases, FooMUS, t)
	test.TestSkip(cases, FooMUS, t)
}
