// Code generated by the AI agent with mus-skill-go. DO NOT EDIT.

package custommode

import (
	"github.com/mus-format/mus-stream-go"
	"github.com/mus-format/mus-stream-go/raw"
	"github.com/mus-format/mus-stream-go/unsafe"
)

var FooMUS = fooMUS{}

type fooMUS struct{}

func (s fooMUS) Marshal(v Foo, w mus.Writer) (n int, err error) {
	n, err = raw.Int.Marshal(v.num, w)
	if err != nil {
		return
	}
	var n1 int
	n1, err = unsafe.String.Marshal(v.str, w)
	n += n1
	return
}

func (s fooMUS) Unmarshal(r mus.Reader) (v Foo, n int, err error) {
	var n1 int
	v.num, n, err = raw.Int.Unmarshal(r)
	if err != nil {
		return
	}
	v.str, n1, err = unsafe.String.Unmarshal(r)
	n += n1
	return
}

func (s fooMUS) Size(v Foo) (size int) {
	size = raw.Int.Size(v.num)
	size += unsafe.String.Size(v.str)
	return
}

func (s fooMUS) Skip(r mus.Reader) (n int, err error) {
	var n1 int
	n, err = raw.Int.Skip(r)
	if err != nil {
		return
	}
	n1, err = unsafe.String.Skip(r)
	n += n1
	return
}
