// Code generated by the AI agent with mus-gen-skill-go. DO NOT EDIT.

package definedtype

import (
	"testing"

	"github.com/mus-format/mus-go/test"
)

func TestFoo(t *testing.T) {
	cases := []Foo{
		Foo(1),
		Foo(2),
		Foo(3),
	}
	test.Test(cases, FooMUS, t)
	test.TestSkip(cases, FooMUS, t)
}
