// Code generated by the AI agent with mus-skill-go. DO NOT EDIT.

package definedtype

import (
	"github.com/mus-format/mus-go/varint"
)

var FooMUS = fooMUS{}

type fooMUS struct{}

func (s fooMUS) Marshal(v Foo, bs []byte) (n int) {
	return varint.Int.Marshal(int(v), bs)
}

func (s fooMUS) Unmarshal(bs []byte) (v Foo, n int, err error) {
	v1, n, err := varint.Int.Unmarshal(bs)
	v = Foo(v1)
	return
}

func (s fooMUS) Size(v Foo) (size int) {
	return varint.Int.Size(int(v))
}

func (s fooMUS) Skip(bs []byte) (n int, err error) {
	return varint.Int.Skip(bs)
}
