// Code generated by the AI agent with mus-skill-go. DO NOT EDIT.

package intr

import (
	"github.com/mus-format/common-go"
	com "github.com/mus-format/common-go"
	"github.com/mus-format/mus-go/ord"
	"github.com/mus-format/mus-go/varint"
)

// Missing DTMs for Interface2 and Interface3
const (
	CarDTM com.DTM = BarDTM + 1
	ZooDTM com.DTM = CarDTM + 1
)

// Interface1 (Foo, Bar)
var Interface1MUS = interface1MUS{}

type interface1MUS struct{}

func (s interface1MUS) Marshal(v Interface1, bs []byte) (n int) {
	switch v1 := v.(type) {
	case Foo:
		n = varint.Uint64.Marshal(uint64(FooDTM), bs)
		n += FooMUS.Marshal(v1, bs[n:])
	case Bar:
		n = varint.Uint64.Marshal(uint64(BarDTM), bs)
		n += BarMUS.Marshal(v1, bs[n:])
	default:
		panic("unknown implementation for Interface1")
	}
	return
}

func (s interface1MUS) Unmarshal(bs []byte) (v Interface1, n int, err error) {
	var (
		dtm uint64
		n1  int
	)
	dtm, n, err = varint.Uint64.Unmarshal(bs)
	if err != nil {
		return
	}
	switch common.DTM(dtm) {
	case FooDTM:
		var impl Foo
		impl, n1, err = FooMUS.Unmarshal(bs[n:])
		v = impl
	case BarDTM:
		var impl Bar
		impl, n1, err = BarMUS.Unmarshal(bs[n:])
		v = impl
	default:
		err = common.ErrUnknownDTM
	}
	n += n1
	return
}

func (s interface1MUS) Size(v Interface1) (size int) {
	switch v1 := v.(type) {
	case Foo:
		size = varint.Uint64.Size(uint64(FooDTM))
		size += FooMUS.Size(v1)
	case Bar:
		size = varint.Uint64.Size(uint64(BarDTM))
		size += BarMUS.Size(v1)
	default:
		panic("unknown implementation for Interface1")
	}
	return
}

func (s interface1MUS) Skip(bs []byte) (n int, err error) {
	var (
		dtm uint64
		n1  int
	)
	dtm, n, err = varint.Uint64.Unmarshal(bs)
	if err != nil {
		return
	}
	switch common.DTM(dtm) {
	case FooDTM:
		n1, err = FooMUS.Skip(bs[n:])
	case BarDTM:
		n1, err = BarMUS.Skip(bs[n:])
	default:
		err = common.ErrUnknownDTM
	}
	n += n1
	return
}

// -----------------------------------------------------------------------------

// Interface2 (Car, Foo)
var Interface2MUS = interface2MUS{}

type interface2MUS struct{}

func (s interface2MUS) Marshal(v Interface2, bs []byte) (n int) {
	switch v1 := v.(type) {
	case Car:
		n = varint.Uint64.Marshal(uint64(CarDTM), bs)
		n += CarMUS.Marshal(v1, bs[n:])
	case Foo:
		n = varint.Uint64.Marshal(uint64(FooDTM), bs)
		n += FooMUS.Marshal(v1, bs[n:])
	default:
		panic("unknown implementation for Interface2")
	}
	return
}

func (s interface2MUS) Unmarshal(bs []byte) (v Interface2, n int, err error) {
	var (
		dtm uint64
		n1  int
	)
	dtm, n, err = varint.Uint64.Unmarshal(bs)
	if err != nil {
		return
	}
	switch common.DTM(dtm) {
	case CarDTM:
		var impl Car
		impl, n1, err = CarMUS.Unmarshal(bs[n:])
		v = impl
	case FooDTM:
		var impl Foo
		impl, n1, err = FooMUS.Unmarshal(bs[n:])
		v = impl
	default:
		err = common.ErrUnknownDTM
	}
	n += n1
	return
}

func (s interface2MUS) Size(v Interface2) (size int) {
	switch v1 := v.(type) {
	case Car:
		size = varint.Uint64.Size(uint64(CarDTM))
		size += CarMUS.Size(v1)
	case Foo:
		size = varint.Uint64.Size(uint64(FooDTM))
		size += FooMUS.Size(v1)
	default:
		panic("unknown implementation for Interface2")
	}
	return
}

func (s interface2MUS) Skip(bs []byte) (n int, err error) {
	var (
		dtm uint64
		n1  int
	)
	dtm, n, err = varint.Uint64.Unmarshal(bs)
	if err != nil {
		return
	}
	switch common.DTM(dtm) {
	case CarDTM:
		n1, err = CarMUS.Skip(bs[n:])
	case FooDTM:
		n1, err = FooMUS.Skip(bs[n:])
	default:
		err = common.ErrUnknownDTM
	}
	n += n1
	return
}

// -----------------------------------------------------------------------------

// Interface3 (Zoo)
var Interface3MUS = interface3MUS{}

type interface3MUS struct{}

func (s interface3MUS) Marshal(v Interface3, bs []byte) (n int) {
	switch v1 := v.(type) {
	case Zoo:
		n = varint.Uint64.Marshal(uint64(ZooDTM), bs)
		n += ZooMUS.Marshal(v1, bs[n:])
	default:
		panic("unknown implementation for Interface3")
	}
	return
}

func (s interface3MUS) Unmarshal(bs []byte) (v Interface3, n int, err error) {
	var (
		dtm uint64
		n1  int
	)
	dtm, n, err = varint.Uint64.Unmarshal(bs)
	if err != nil {
		return
	}
	switch common.DTM(dtm) {
	case ZooDTM:
		var impl Zoo
		impl, n1, err = ZooMUS.Unmarshal(bs[n:])
		v = impl
	default:
		err = common.ErrUnknownDTM
	}
	n += n1
	return
}

func (s interface3MUS) Size(v Interface3) (size int) {
	switch v1 := v.(type) {
	case Zoo:
		size = varint.Uint64.Size(uint64(ZooDTM))
		size += ZooMUS.Size(v1)
	default:
		panic("unknown implementation for Interface3")
	}
	return
}

func (s interface3MUS) Skip(bs []byte) (n int, err error) {
	var (
		dtm uint64
		n1  int
	)
	dtm, n, err = varint.Uint64.Unmarshal(bs)
	if err != nil {
		return
	}
	switch common.DTM(dtm) {
	case ZooDTM:
		n1, err = ZooMUS.Skip(bs[n:])
	default:
		err = common.ErrUnknownDTM
	}
	n += n1
	return
}

// -----------------------------------------------------------------------------

var FooMUS = fooMUS{}

type fooMUS struct{}

func (s fooMUS) Marshal(v Foo, bs []byte) (n int) {
	return varint.Int.Marshal(v.Num, bs)
}

func (s fooMUS) Unmarshal(bs []byte) (v Foo, n int, err error) {
	v.Num, n, err = varint.Int.Unmarshal(bs)
	return
}

func (s fooMUS) Size(v Foo) (size int) {
	return varint.Int.Size(v.Num)
}

func (s fooMUS) Skip(bs []byte) (n int, err error) {
	return varint.Int.Skip(bs)
}

// -----------------------------------------------------------------------------

var BarMUS = barMUS{}

type barMUS struct{}

func (s barMUS) Marshal(v Bar, bs []byte) (n int) {
	return ord.String.Marshal(string(v), bs)
}

func (s barMUS) Unmarshal(bs []byte) (v Bar, n int, err error) {
	v1, n, err := ord.String.Unmarshal(bs)
	v = Bar(v1)
	return
}

func (s barMUS) Size(v Bar) (size int) {
	return ord.String.Size(string(v))
}

func (s barMUS) Skip(bs []byte) (n int, err error) {
	return ord.String.Skip(bs)
}

// -----------------------------------------------------------------------------

var ZooMUS = zooMUS{}

type zooMUS struct{}

func (s zooMUS) Marshal(v Zoo, bs []byte) (n int) {
	return ord.Bool.Marshal(bool(v), bs)
}

func (s zooMUS) Unmarshal(bs []byte) (v Zoo, n int, err error) {
	v1, n, err := ord.Bool.Unmarshal(bs)
	v = Zoo(v1)
	return
}

func (s zooMUS) Size(v Zoo) (size int) {
	return ord.Bool.Size(bool(v))
}

func (s zooMUS) Skip(bs []byte) (n int, err error) {
	return ord.Bool.Skip(bs)
}

// -----------------------------------------------------------------------------

var CarMUS = carMUS{}

type carMUS struct{}

func (s carMUS) Marshal(v Car, bs []byte) (n int) {
	return varint.Float32.Marshal(v.float, bs)
}

func (s carMUS) Unmarshal(bs []byte) (v Car, n int, err error) {
	v.float, n, err = varint.Float32.Unmarshal(bs)
	return
}

func (s carMUS) Size(v Car) (size int) {
	return varint.Float32.Size(v.float)
}

func (s carMUS) Skip(bs []byte) (n int, err error) {
	return varint.Float32.Skip(bs)
}
