// Code generated by the AI agent with mus-gen-skill-go. DO NOT EDIT.

package sers

import (
	"image"

	"github.com/mus-format/mus-gen-skill-go/test/mus-stream-go/complex/sub1"
	"github.com/mus-format/mus-gen-skill-go/test/mus-stream-go/complex/sub2"
	"github.com/mus-format/mus-stream-go"
	"github.com/mus-format/mus-stream-go/ord"
	"github.com/mus-format/mus-stream-go/varint"
)

// Bar1 (sub1.Bar, mus:name = Bar1)
var Bar1 = bar1MUS{}

type bar1MUS struct{}

func (s bar1MUS) Marshal(v sub1.Bar, w mus.Writer) (n int, err error) {
	return varint.Int.Marshal(v.Int, w)
}

func (s bar1MUS) Unmarshal(r mus.Reader) (v sub1.Bar, n int, err error) {
	v.Int, n, err = varint.Int.Unmarshal(r)
	return
}

func (s bar1MUS) Size(v sub1.Bar) (size int) {
	return varint.Int.Size(v.Int)
}

func (s bar1MUS) Skip(r mus.Reader) (n int, err error) {
	return varint.Int.Skip(r)
}

// -----------------------------------------------------------------------------

// Bar2 (sub2.Bar, mus:name = Bar2)
var Bar2 = bar2MUS{}

type bar2MUS struct{}

func (s bar2MUS) Marshal(v sub2.Bar, w mus.Writer) (n int, err error) {
	return ord.String.Marshal(v.Str, w)
}

func (s bar2MUS) Unmarshal(r mus.Reader) (v sub2.Bar, n int, err error) {
	v.Str, n, err = ord.String.Unmarshal(r)
	return
}

func (s bar2MUS) Size(v sub2.Bar) (size int) {
	return ord.String.Size(v.Str)
}

func (s bar2MUS) Skip(r mus.Reader) (n int, err error) {
	return ord.String.Skip(r)
}

// -----------------------------------------------------------------------------

// Point (image.Point)
var Point = pointMUS{}

type pointMUS struct{}

func (s pointMUS) Marshal(v image.Point, w mus.Writer) (n int, err error) {
	n, err = varint.Int.Marshal(v.X, w)
	if err != nil {
		return
	}
	var n1 int
	n1, err = varint.Int.Marshal(v.Y, w)
	n += n1
	return
}

func (s pointMUS) Unmarshal(r mus.Reader) (v image.Point, n int, err error) {
	var n1 int
	v.X, n, err = varint.Int.Unmarshal(r)
	if err != nil {
		return
	}
	v.Y, n1, err = varint.Int.Unmarshal(r)
	n += n1
	return
}

func (s pointMUS) Size(v image.Point) (size int) {
	size = varint.Int.Size(v.X)
	size += varint.Int.Size(v.Y)
	return
}

func (s pointMUS) Skip(r mus.Reader) (n int, err error) {
	var n1 int
	n, err = varint.Int.Skip(r)
	if err != nil {
		return
	}
	n1, err = varint.Int.Skip(r)
	n += n1
	return
}
