// Code generated by the AI agent with mus-skill-go. DO NOT EDIT.

package structure

import (
	"github.com/mus-format/mus-stream-go"
	"github.com/mus-format/mus-stream-go/ord"
	"github.com/mus-format/mus-stream-go/varint"
)

var FooMUS = fooMUS{}

type fooMUS struct{}

func (s fooMUS) Marshal(v Foo, w mus.Writer) (n int, err error) {
	n, err = varint.Int8.Marshal(v.num, w)
	if err != nil {
		return
	}
	var n1 int
	n1, err = ord.String.Marshal(v.str, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.ByteSlice.Marshal(v.sl, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.NewMapSer(varint.Float64, varint.Int32).Marshal(v.mp, w)
	n += n1
	return
}

func (s fooMUS) Unmarshal(r mus.Reader) (v Foo, n int, err error) {
	v.num, n, err = varint.Int8.Unmarshal(r)
	if err != nil {
		return
	}
	var n1 int
	v.str, n1, err = ord.String.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.sl, n1, err = ord.ByteSlice.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.mp, n1, err = ord.NewMapSer(varint.Float64, varint.Int32).Unmarshal(r)
	n += n1
	return
}

func (s fooMUS) Size(v Foo) (size int) {
	size = varint.Int8.Size(v.num)
	size += ord.String.Size(v.str)
	size += ord.ByteSlice.Size(v.sl)
	size += ord.NewMapSer(varint.Float64, varint.Int32).Size(v.mp)
	return
}

func (s fooMUS) Skip(r mus.Reader) (n int, err error) {
	n, err = varint.Int8.Skip(r)
	if err != nil {
		return
	}
	var n1 int
	n1, err = ord.String.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.ByteSlice.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.NewMapSer(varint.Float64, varint.Int32).Skip(r)
	n += n1
	return
}
