// Code generated by the AI agent with mus-skill-go. DO NOT EDIT.

package intr

import (
	"github.com/mus-format/common-go"
	com "github.com/mus-format/common-go"
	"github.com/mus-format/mus-stream-go"
	"github.com/mus-format/mus-stream-go/ord"
	"github.com/mus-format/mus-stream-go/varint"
)

// Missing DTMs for Interface2 and Interface3
const (
	CarDTM com.DTM = BarDTM + 1
	ZooDTM com.DTM = CarDTM + 1
)

// Interface1 (Foo, Bar)
var Interface1MUS = interface1MUS{}

type interface1MUS struct{}

func (s interface1MUS) Marshal(v Interface1, w mus.Writer) (n int, err error) {
	switch v1 := v.(type) {
	case Foo:
		n, err = varint.Uint64.Marshal(uint64(FooDTM), w)
		if err != nil {
			return
		}
		var n1 int
		n1, err = FooMUS.Marshal(v1, w)
		n += n1
	case Bar:
		n, err = varint.Uint64.Marshal(uint64(BarDTM), w)
		if err != nil {
			return
		}
		var n1 int
		n1, err = BarMUS.Marshal(v1, w)
		n += n1
	default:
		panic("unknown implementation for Interface1")
	}
	return
}

func (s interface1MUS) Unmarshal(r mus.Reader) (v Interface1, n int, err error) {
	var (
		dtm uint64
		n1  int
	)
	dtm, n, err = varint.Uint64.Unmarshal(r)
	if err != nil {
		return
	}
	switch common.DTM(dtm) {
	case FooDTM:
		var impl Foo
		impl, n1, err = FooMUS.Unmarshal(r)
		v = impl
	case BarDTM:
		var impl Bar
		impl, n1, err = BarMUS.Unmarshal(r)
		v = impl
	default:
		err = common.ErrUnknownDTM
	}
	n += n1
	return
}

func (s interface1MUS) Size(v Interface1) (size int) {
	switch v1 := v.(type) {
	case Foo:
		size = varint.Uint64.Size(uint64(FooDTM))
		size += FooMUS.Size(v1)
	case Bar:
		size = varint.Uint64.Size(uint64(BarDTM))
		size += BarMUS.Size(v1)
	default:
		panic("unknown implementation for Interface1")
	}
	return
}

func (s interface1MUS) Skip(r mus.Reader) (n int, err error) {
	var (
		dtm uint64
		n1  int
	)
	dtm, n, err = varint.Uint64.Unmarshal(r)
	if err != nil {
		return
	}
	switch common.DTM(dtm) {
	case FooDTM:
		n1, err = FooMUS.Skip(r)
	case BarDTM:
		n1, err = BarMUS.Skip(r)
	default:
		err = common.ErrUnknownDTM
	}
	n += n1
	return
}

// -----------------------------------------------------------------------------

// Interface2 (Car, Foo)
var Interface2MUS = interface2MUS{}

type interface2MUS struct{}

func (s interface2MUS) Marshal(v Interface2, w mus.Writer) (n int, err error) {
	switch v1 := v.(type) {
	case Car:
		n, err = varint.Uint64.Marshal(uint64(CarDTM), w)
		if err != nil {
			return
		}
		var n1 int
		n1, err = CarMUS.Marshal(v1, w)
		n += n1
	case Foo:
		n, err = varint.Uint64.Marshal(uint64(FooDTM), w)
		if err != nil {
			return
		}
		var n1 int
		n1, err = FooMUS.Marshal(v1, w)
		n += n1
	default:
		panic("unknown implementation for Interface2")
	}
	return
}

func (s interface2MUS) Unmarshal(r mus.Reader) (v Interface2, n int, err error) {
	var (
		dtm uint64
		n1  int
	)
	dtm, n, err = varint.Uint64.Unmarshal(r)
	if err != nil {
		return
	}
	switch common.DTM(dtm) {
	case CarDTM:
		var impl Car
		impl, n1, err = CarMUS.Unmarshal(r)
		v = impl
	case FooDTM:
		var impl Foo
		impl, n1, err = FooMUS.Unmarshal(r)
		v = impl
	default:
		err = common.ErrUnknownDTM
	}
	n += n1
	return
}

func (s interface2MUS) Size(v Interface2) (size int) {
	switch v1 := v.(type) {
	case Car:
		size = varint.Uint64.Size(uint64(CarDTM))
		size += CarMUS.Size(v1)
	case Foo:
		size = varint.Uint64.Size(uint64(FooDTM))
		size += FooMUS.Size(v1)
	default:
		panic("unknown implementation for Interface2")
	}
	return
}

func (s interface2MUS) Skip(r mus.Reader) (n int, err error) {
	var (
		dtm uint64
		n1  int
	)
	dtm, n, err = varint.Uint64.Unmarshal(r)
	if err != nil {
		return
	}
	switch common.DTM(dtm) {
	case CarDTM:
		n1, err = CarMUS.Skip(r)
	case FooDTM:
		n1, err = FooMUS.Skip(r)
	default:
		err = common.ErrUnknownDTM
	}
	n += n1
	return
}

// -----------------------------------------------------------------------------

// Interface3 (Zoo)
var Interface3MUS = interface3MUS{}

type interface3MUS struct{}

func (s interface3MUS) Marshal(v Interface3, w mus.Writer) (n int, err error) {
	switch v1 := v.(type) {
	case Zoo:
		n, err = varint.Uint64.Marshal(uint64(ZooDTM), w)
		if err != nil {
			return
		}
		var n1 int
		n1, err = ZooMUS.Marshal(v1, w)
		n += n1
	default:
		panic("unknown implementation for Interface3")
	}
	return
}

func (s interface3MUS) Unmarshal(r mus.Reader) (v Interface3, n int, err error) {
	var (
		dtm uint64
		n1  int
	)
	dtm, n, err = varint.Uint64.Unmarshal(r)
	if err != nil {
		return
	}
	switch common.DTM(dtm) {
	case ZooDTM:
		var impl Zoo
		impl, n1, err = ZooMUS.Unmarshal(r)
		v = impl
	default:
		err = common.ErrUnknownDTM
	}
	n += n1
	return
}

func (s interface3MUS) Size(v Interface3) (size int) {
	switch v1 := v.(type) {
	case Zoo:
		size = varint.Uint64.Size(uint64(ZooDTM))
		size += ZooMUS.Size(v1)
	default:
		panic("unknown implementation for Interface3")
	}
	return
}

func (s interface3MUS) Skip(r mus.Reader) (n int, err error) {
	var (
		dtm uint64
		n1  int
	)
	dtm, n, err = varint.Uint64.Unmarshal(r)
	if err != nil {
		return
	}
	switch common.DTM(dtm) {
	case ZooDTM:
		n1, err = ZooMUS.Skip(r)
	default:
		err = common.ErrUnknownDTM
	}
	n += n1
	return
}

// -----------------------------------------------------------------------------

var FooMUS = fooMUS{}

type fooMUS struct{}

func (s fooMUS) Marshal(v Foo, w mus.Writer) (n int, err error) {
	return varint.Int.Marshal(v.Num, w)
}

func (s fooMUS) Unmarshal(r mus.Reader) (v Foo, n int, err error) {
	v.Num, n, err = varint.Int.Unmarshal(r)
	return
}

func (s fooMUS) Size(v Foo) (size int) {
	return varint.Int.Size(v.Num)
}

func (s fooMUS) Skip(r mus.Reader) (n int, err error) {
	return varint.Int.Skip(r)
}

// -----------------------------------------------------------------------------

var BarMUS = barMUS{}

type barMUS struct{}

func (s barMUS) Marshal(v Bar, w mus.Writer) (n int, err error) {
	return ord.String.Marshal(string(v), w)
}

func (s barMUS) Unmarshal(r mus.Reader) (v Bar, n int, err error) {
	v1, n, err := ord.String.Unmarshal(r)
	v = Bar(v1)
	return
}

func (s barMUS) Size(v Bar) (size int) {
	return ord.String.Size(string(v))
}

func (s barMUS) Skip(r mus.Reader) (n int, err error) {
	return ord.String.Skip(r)
}

// -----------------------------------------------------------------------------

var ZooMUS = zooMUS{}

type zooMUS struct{}

func (s zooMUS) Marshal(v Zoo, w mus.Writer) (n int, err error) {
	return ord.Bool.Marshal(bool(v), w)
}

func (s zooMUS) Unmarshal(r mus.Reader) (v Zoo, n int, err error) {
	v1, n, err := ord.Bool.Unmarshal(r)
	v = Zoo(v1)
	return
}

func (s zooMUS) Size(v Zoo) (size int) {
	return ord.Bool.Size(bool(v))
}

func (s zooMUS) Skip(r mus.Reader) (n int, err error) {
	return ord.Bool.Skip(r)
}

// -----------------------------------------------------------------------------

var CarMUS = carMUS{}

type carMUS struct{}

func (s carMUS) Marshal(v Car, w mus.Writer) (n int, err error) {
	return varint.Float32.Marshal(v.float, w)
}

func (s carMUS) Unmarshal(r mus.Reader) (v Car, n int, err error) {
	v.float, n, err = varint.Float32.Unmarshal(r)
	return
}

func (s carMUS) Size(v Car) (size int) {
	return varint.Float32.Size(v.float)
}

func (s carMUS) Skip(r mus.Reader) (n int, err error) {
	return varint.Float32.Skip(r)
}
