// Code generated by the AI agent with mus-skill-go. DO NOT EDIT.

package intr

import (
	"testing"

	"github.com/mus-format/mus-stream-go/test"
)

func TestInterface(t *testing.T) {
	// Interface1
	t.Run("Interface1", func(t *testing.T) {
		cases := []Interface1{
			Foo{Num: 1},
			Bar("bar"),
		}
		test.Test(cases, Interface1MUS, t)
		test.TestSkip(cases, Interface1MUS, t)
	})

	// Interface2
	t.Run("Interface2", func(t *testing.T) {
		cases := []Interface2{
			Car{float: 1.1},
			Foo{Num: 2},
		}
		test.Test(cases, Interface2MUS, t)
		test.TestSkip(cases, Interface2MUS, t)
	})

	// Interface3
	t.Run("Interface3", func(t *testing.T) {
		cases := []Interface3{
			Zoo(true),
			Zoo(false),
		}
		test.Test(cases, Interface3MUS, t)
		test.TestSkip(cases, Interface3MUS, t)
	})
}
