// Code generated by AI agent with mus-skill. DO NOT EDIT.

package custom

import (
	"fmt"

	com "github.com/mus-format/common-go"
	"github.com/mus-format/mus-go/ord"
	"github.com/mus-format/mus-go/raw"
	"github.com/mus-format/mus-go/typed"
	"github.com/mus-format/mus-go/unsafe"
	"github.com/mus-format/mus-go/varint"
	"github.com/mus-format/mus-skill-go/test/mode"
)

// FullDefinedMUS
var FullDefinedMUS = fullDefinedMUS{}

type fullDefinedMUS struct{}

func (s fullDefinedMUS) Marshal(v mode.FullDefined, bs []byte) (n int) {
	return varint.PositiveInt.Marshal(int(v), bs)
}

func (s fullDefinedMUS) Unmarshal(bs []byte) (v mode.FullDefined, n int, err error) {
	tmp, n, err := varint.PositiveInt.Unmarshal(bs)
	if err != nil {
		return
	}
	v = mode.FullDefined(tmp)
	return
}

func (s fullDefinedMUS) Size(v mode.FullDefined) (size int) {
	return varint.PositiveInt.Size(int(v))
}

func (s fullDefinedMUS) Skip(bs []byte) (n int, err error) {
	return varint.PositiveInt.Skip(bs)
}

// FullInterfaceImplMUS
var FullInterfaceImplMUS = fullInterfaceImplMUS{}

type fullInterfaceImplMUS struct{}

func (s fullInterfaceImplMUS) Marshal(v mode.FullInterfaceImpl, bs []byte) (n int) {
	return unsafe.String.Marshal(string(v), bs)
}

func (s fullInterfaceImplMUS) Unmarshal(bs []byte) (v mode.FullInterfaceImpl, n int, err error) {
	tmp, n, err := unsafe.String.Unmarshal(bs)
	if err != nil {
		return
	}
	v = mode.FullInterfaceImpl(tmp)
	return
}

func (s fullInterfaceImplMUS) Size(v mode.FullInterfaceImpl) (size int) {
	return unsafe.String.Size(string(v))
}

func (s fullInterfaceImplMUS) Skip(bs []byte) (n int, err error) {
	return unsafe.String.Skip(bs)
}

// DTM constants
const (
	FullInterfaceImplDTM com.DTM = 1
)

// Typed serializers
var (
	FullInterfaceImplTypedMUS = typed.NewTypedSer(FullInterfaceImplDTM, FullInterfaceImplMUS)
)

// FullInterfaceMUS
var FullInterfaceMUS = fullInterfaceMUS{}

type fullInterfaceMUS struct{}

func (s fullInterfaceMUS) Marshal(v mode.FullInterface, bs []byte) (n int) {
	if v == nil {
		return ord.Bool.Marshal(true, bs)
	}
	n = ord.Bool.Marshal(false, bs)
	switch val := v.(type) {
	case mode.FullInterfaceImpl:
		return n + FullInterfaceImplTypedMUS.Marshal(val, bs[n:])
	default:
		panic(fmt.Sprintf(com.ErrorPrefix+"unexpected %v type", v))
	}
}

func (s fullInterfaceMUS) Unmarshal(bs []byte) (v mode.FullInterface, n int, err error) {
	isNil, n, err := ord.Bool.Unmarshal(bs)
	if err != nil || isNil {
		return
	}
	var n1 int
	dtm, n1, err := typed.DTMSer.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	switch dtm {
	case FullInterfaceImplDTM:
		var tmp mode.FullInterfaceImpl
		tmp, n1, err = FullInterfaceImplTypedMUS.UnmarshalData(bs[n:])
		if err != nil {
			return
		}
		v = tmp
		n += n1
	default:
		err = com.NewUnexpectedDTMError(dtm)
		return
	}
	return
}

func (s fullInterfaceMUS) Size(v mode.FullInterface) (size int) {
	if v == nil {
		return ord.Bool.Size(true)
	}
	size = ord.Bool.Size(false)
	switch val := v.(type) {
	case mode.FullInterfaceImpl:
		return size + FullInterfaceImplTypedMUS.Size(val)
	default:
		panic(fmt.Sprintf(com.ErrorPrefix+"unexpected %v type", v))
	}
}

func (s fullInterfaceMUS) Skip(bs []byte) (n int, err error) {
	isNil, n, err := ord.Bool.Unmarshal(bs)
	if err != nil || isNil {
		return
	}
	var n1 int
	dtm, n1, err := typed.DTMSer.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	switch dtm {
	case FullInterfaceImplDTM:
		n1, err = FullInterfaceImplTypedMUS.SkipData(bs[n:])
	default:
		err = com.NewUnexpectedDTMError(dtm)
		return
	}
	n += n1
	return
}

// Anonymous serializers
var (
	ptrInt     = ord.NewPtrSer(varint.PositiveInt)
	arrayInt   = unsafe.NewArraySer[[10]int, int](varint.PositiveInt)
	sliceInt   = ord.NewSliceSer(varint.PositiveInt)
	mapStrInt  = ord.NewMapSer(unsafe.String, varint.PositiveInt)
	uint8Slice = ord.NewSliceSer(raw.Uint8)
)

// FullStructMUS
var FullStructMUS = fullStructMUS{}

type fullStructMUS struct{}

func (s fullStructMUS) Marshal(v mode.FullStruct, bs []byte) (n int) {
	n = varint.PositiveInt.Marshal(v.Int, bs)
	n += varint.PositiveInt64.Marshal(v.Int64, bs[n:])
	n += varint.PositiveInt32.Marshal(v.Int32, bs[n:])
	n += varint.PositiveInt16.Marshal(v.Int16, bs[n:])
	n += varint.Int8.Marshal(v.Int8, bs[n:])
	n += raw.Uint.Marshal(v.Uint, bs[n:])
	n += raw.Uint64.Marshal(v.Uint64, bs[n:])
	n += raw.Uint32.Marshal(v.Uint32, bs[n:])
	n += raw.Uint16.Marshal(v.Uint16, bs[n:])
	n += raw.Uint8.Marshal(v.Uint8, bs[n:])
	n += unsafe.Float64.Marshal(v.Float64, bs[n:])
	n += unsafe.Float32.Marshal(v.Float32, bs[n:])
	n += raw.Uint8.Marshal(v.Byte, bs[n:])
	n += ord.Bool.Marshal(v.Bool, bs[n:])
	n += unsafe.String.Marshal(v.Str, bs[n:])
	n += ord.ByteSlice.Marshal(v.ByteSlice, bs[n:])
	n += uint8Slice.Marshal(v.Uint8Slice, bs[n:])
	n += unsafe.TimeUnixMicro.Marshal(v.Time, bs[n:])
	n += ptrInt.Marshal(v.PtrInt, bs[n:])
	n += arrayInt.Marshal(v.ArrayInt, bs[n:])
	n += sliceInt.Marshal(v.SliceInt, bs[n:])
	n += mapStrInt.Marshal(v.MapStrInt, bs[n:])
	n += FullDefinedMUS.Marshal(v.Defined, bs[n:])
	n += FullInterfaceMUS.Marshal(v.Interface, bs[n:])
	return n
}

func (s fullStructMUS) Unmarshal(bs []byte) (v mode.FullStruct, n int, err error) {
	var n1 int
	v.Int, n1, err = varint.PositiveInt.Unmarshal(bs)
	n += n1
	if err != nil {
		return
	}
	v.Int64, n1, err = varint.PositiveInt64.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Int32, n1, err = varint.PositiveInt32.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Int16, n1, err = varint.PositiveInt16.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Int8, n1, err = varint.Int8.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Uint, n1, err = raw.Uint.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Uint64, n1, err = raw.Uint64.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Uint32, n1, err = raw.Uint32.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Uint16, n1, err = raw.Uint16.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Uint8, n1, err = raw.Uint8.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Float64, n1, err = unsafe.Float64.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Float32, n1, err = unsafe.Float32.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Byte, n1, err = raw.Uint8.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Bool, n1, err = ord.Bool.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Str, n1, err = unsafe.String.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.ByteSlice, n1, err = ord.ByteSlice.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Uint8Slice, n1, err = uint8Slice.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Time, n1, err = unsafe.TimeUnixMicro.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.PtrInt, n1, err = ptrInt.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.ArrayInt, n1, err = arrayInt.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.SliceInt, n1, err = sliceInt.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.MapStrInt, n1, err = mapStrInt.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Defined, n1, err = FullDefinedMUS.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Interface, n1, err = FullInterfaceMUS.Unmarshal(bs[n:])
	n += n1
	return
}

func (s fullStructMUS) Size(v mode.FullStruct) (size int) {
	size = varint.PositiveInt.Size(v.Int)
	size += varint.PositiveInt64.Size(v.Int64)
	size += varint.PositiveInt32.Size(v.Int32)
	size += varint.PositiveInt16.Size(v.Int16)
	size += varint.Int8.Size(v.Int8)
	size += raw.Uint.Size(v.Uint)
	size += raw.Uint64.Size(v.Uint64)
	size += raw.Uint32.Size(v.Uint32)
	size += raw.Uint16.Size(v.Uint16)
	size += raw.Uint8.Size(v.Uint8)
	size += unsafe.Float64.Size(v.Float64)
	size += unsafe.Float32.Size(v.Float32)
	size += raw.Uint8.Size(v.Byte)
	size += ord.Bool.Size(v.Bool)
	size += unsafe.String.Size(v.Str)
	size += ord.ByteSlice.Size(v.ByteSlice)
	size += uint8Slice.Size(v.Uint8Slice)
	size += unsafe.TimeUnixMicro.Size(v.Time)
	size += ptrInt.Size(v.PtrInt)
	size += arrayInt.Size(v.ArrayInt)
	size += sliceInt.Size(v.SliceInt)
	size += mapStrInt.Size(v.MapStrInt)
	size += FullDefinedMUS.Size(v.Defined)
	size += FullInterfaceMUS.Size(v.Interface)
	return size
}

func (s fullStructMUS) Skip(bs []byte) (n int, err error) {
	var n1 int
	n1, err = varint.PositiveInt.Skip(bs)
	n += n1
	if err != nil {
		return
	}
	n1, err = varint.PositiveInt64.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = varint.PositiveInt32.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = varint.PositiveInt16.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = varint.Int8.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = raw.Uint.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = raw.Uint64.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = raw.Uint32.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = raw.Uint16.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = raw.Uint8.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Float64.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Float32.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = raw.Uint8.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.Bool.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.String.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.ByteSlice.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = uint8Slice.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.TimeUnixMicro.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = ptrInt.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = arrayInt.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = sliceInt.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = mapStrInt.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = FullDefinedMUS.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = FullInterfaceMUS.Skip(bs[n:])
	n += n1
	return
}
