// Code generated by AI agent with mus-skill. DO NOT EDIT.

package custom

import (
	"testing"
	"time"

	"github.com/mus-format/mus-go/test"
	"github.com/mus-format/mus-skill-go/test/mode"
)

func TestFullStruct(t *testing.T) {
	ptr := new(int)
	*ptr = 100
	cases := []mode.FullStruct{
		{
			Int:        1,
			Int64:      2,
			Int32:      3,
			Int16:      4,
			Int8:       5,
			Uint:       6,
			Uint64:     7,
			Uint32:     8,
			Uint16:     9,
			Uint8:      10,
			Float64:    11.1,
			Float32:    12.2,
			Byte:       13,
			Bool:       true,
			Str:        "14",
			ByteSlice:  []byte{15},
			Uint8Slice: []uint8{16},
			Time:       time.Unix(17, 0),
			PtrInt:     ptr,
			ArrayInt:   [10]int{18},
			SliceInt:   []int{19},
			MapStrInt:  map[string]int{"20": 21},
			Defined:    22,
			Interface:  mode.FullInterfaceImpl("23"),
		},
		{
			ByteSlice:  []byte{},
			Uint8Slice: []uint8{},
			SliceInt:   []int{},
			MapStrInt:  map[string]int{},
			Time:       time.Unix(1, 0),
		},
	}

	test.Test(cases, FullStructMUS, t)
	test.TestSkip(cases, FullStructMUS, t)
}

func TestFullDefined(t *testing.T) {
	cases := []mode.FullDefined{0, 1, -1, 100}
	test.Test(cases, FullDefinedMUS, t)
	test.TestSkip(cases, FullDefinedMUS, t)
}

func TestFullInterfaceImpl(t *testing.T) {
	cases := []mode.FullInterfaceImpl{"", "hi"}
	test.Test(cases, FullInterfaceImplMUS, t)
	test.TestSkip(cases, FullInterfaceImplMUS, t)
}
