// Code generated by AI agent with mus-skill. DO NOT EDIT.

package custom_sername

import (
	"image"
	"testing"

	"github.com/mus-format/mus-go/test"
)

func TestFoo(t *testing.T) {
	cases := []Foo{
		{Point: image.Point{X: 0, Y: 0}},
		{Point: image.Point{X: 1, Y: 1}},
		{Point: image.Point{X: -1, Y: -1}},
		{Point: image.Point{X: 100, Y: 200}},
	}
	test.Test(cases, CustomFooMUS, t)
	test.TestSkip(cases, CustomFooMUS, t)
}
