// Code generated by AI agent with mus-skill. DO NOT EDIT.

package custom_sername

import (
	"github.com/mus-format/mus-skill-go/test/genopts/custom_sername/pkg"
)

// CustomFooMUS
var CustomFooMUS = customFooMUS{}

type customFooMUS struct{}

func (s customFooMUS) Marshal(v Foo, bs []byte) (n int) {
	return pkg.PointMUS.Marshal(v.Point, bs)
}

func (s customFooMUS) Unmarshal(bs []byte) (v Foo, n int, err error) {
	v.Point, n, err = pkg.PointMUS.Unmarshal(bs)
	return
}

func (s customFooMUS) Size(v Foo) (size int) {
	return pkg.PointMUS.Size(v.Point)
}

func (s customFooMUS) Skip(bs []byte) (n int, err error) {
	return pkg.PointMUS.Skip(bs)
}
