// Code generated by the AI agent with mus-gen-skill-go. DO NOT EDIT.

package complex

import (
	"github.com/mus-format/common-go"
	"github.com/mus-format/mus-gen-skill-go/test/mus-stream-go/complex/sers"
	"github.com/mus-format/mus-gen-skill-go/test/mus-stream-go/complex/validators"
	"github.com/mus-format/mus-stream-go"
	mapopts "github.com/mus-format/mus-stream-go/options/map"
	slopts "github.com/mus-format/mus-stream-go/options/slice"
	"github.com/mus-format/mus-stream-go/ord"
	"github.com/mus-format/mus-stream-go/raw"
	"github.com/mus-format/mus-stream-go/varint"
)

// ComplexFooMUS (mus:name = ComplexFooMUS)
var ComplexFooMUS = complexFooMUS{}

type complexFooMUS struct{}

func (s complexFooMUS) Marshal(v Foo, w mus.Writer) (n int, err error) {
	n, err = varint.Int.Marshal(v.Num, w)
	if err != nil {
		return
	}
	var n1 int
	n1, err = raw.Int.Marshal(v.RawNum, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = ValidStringMUS.Marshal(v.Str, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = CustomSliceMUS.Marshal(v.Sl, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = CustomMapMUS.Marshal(v.Map, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.NewPtrSer(varint.Int).Marshal(v.Ptr, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = sers.Bar1.Marshal(v.Bar1, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = sers.Bar2.Marshal(v.Bar2, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = sers.Point.Marshal(v.Point, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = EmbeddedMUS.Marshal(v.Embedded, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.NewSliceSer(
		ord.NewSliceSer(
			stringWithValidatorMUS{common.ValidatorFn[string](validators.ValidateString)},
			slopts.WithLenSer[string](raw.Int),
		),
		slopts.WithLenSer[[]string](raw.Int),
	).Marshal(v.sl, w)
	n += n1
	return
}

func (s complexFooMUS) Unmarshal(r mus.Reader) (v Foo, n int, err error) {
	var n1 int
	v.Num, n, err = varint.Int.Unmarshal(r)
	if err != nil {
		return
	}
	if err = validators.ValidateInt(v.Num); err != nil {
		return
	}
	v.RawNum, n1, err = raw.Int.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Str, n1, err = ValidStringMUS.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Sl, n1, err = CustomSliceMUS.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Map, n1, err = CustomMapMUS.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Ptr, n1, err = ord.NewPtrSer(varint.Int).Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Bar1, n1, err = sers.Bar1.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Bar2, n1, err = sers.Bar2.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Point, n1, err = sers.Point.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Embedded, n1, err = EmbeddedMUS.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.sl, n1, err = ord.NewSliceSer(
		ord.NewSliceSer(
			stringWithValidatorMUS{common.ValidatorFn[string](validators.ValidateString)},
			slopts.WithLenSer[string](raw.Int),
		),
		slopts.WithLenSer[[]string](raw.Int),
	).Unmarshal(r)
	n += n1
	return
}

func (s complexFooMUS) Size(v Foo) (size int) {
	size = varint.Int.Size(v.Num)
	size += raw.Int.Size(v.RawNum)
	size += ValidStringMUS.Size(v.Str)
	size += CustomSliceMUS.Size(v.Sl)
	size += CustomMapMUS.Size(v.Map)
	size += ord.NewPtrSer(varint.Int).Size(v.Ptr)
	size += sers.Bar1.Size(v.Bar1)
	size += sers.Bar2.Size(v.Bar2)
	size += sers.Point.Size(v.Point)
	size += EmbeddedMUS.Size(v.Embedded)
	size += ord.NewSliceSer(
		ord.NewSliceSer(
			stringWithValidatorMUS{common.ValidatorFn[string](validators.ValidateString)},
			slopts.WithLenSer[string](raw.Int),
		),
		slopts.WithLenSer[[]string](raw.Int),
	).Size(v.sl)
	return
}

func (s complexFooMUS) Skip(r mus.Reader) (n int, err error) {
	var n1 int
	n, err = varint.Int.Skip(r)
	if err != nil {
		return
	}
	n1, err = raw.Int.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = ValidStringMUS.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = CustomSliceMUS.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = CustomMapMUS.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.NewPtrSer(varint.Int).Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = sers.Bar1.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = sers.Bar2.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = sers.Point.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = EmbeddedMUS.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.NewSliceSer(
		ord.NewSliceSer(
			stringWithValidatorMUS{common.ValidatorFn[string](validators.ValidateString)},
			slopts.WithLenSer[string](raw.Int),
		),
		slopts.WithLenSer[[]string](raw.Int),
	).Skip(r)
	n += n1
	return
}

// -----------------------------------------------------------------------------

var ValidStringMUS = validStringMUS{}

type validStringMUS struct{}

func (s validStringMUS) Marshal(v ValidString, w mus.Writer) (n int, err error) {
	return ord.String.Marshal(string(v), w)
}

func (s validStringMUS) Unmarshal(r mus.Reader) (v ValidString, n int, err error) {
	v1, n, err := ord.String.Unmarshal(r)
	v = ValidString(v1)
	if err != nil {
		return
	}
	err = validators.ValidateString(string(v))
	return
}

func (s validStringMUS) Size(v ValidString) (size int) {
	return ord.String.Size(string(v))
}

func (s validStringMUS) Skip(r mus.Reader) (n int, err error) {
	return ord.String.Skip(r)
}

// -----------------------------------------------------------------------------

var CustomSliceMUS = customSliceMUS{}

type customSliceMUS struct{}

var customSliceSerializer = ord.NewValidSliceSer(
	varint.Int,
	slopts.WithLenSer[int](raw.Int),
	slopts.WithElemValidator[int](common.ValidatorFn[int](validators.ValidateSliceElem)),
)

func (s customSliceMUS) Marshal(v CustomSlice, w mus.Writer) (n int, err error) {
	return customSliceSerializer.Marshal([]int(v), w)
}

func (s customSliceMUS) Unmarshal(r mus.Reader) (v CustomSlice, n int, err error) {
	v1, n, err := customSliceSerializer.Unmarshal(r)
	v = CustomSlice(v1)
	return
}

func (s customSliceMUS) Size(v CustomSlice) (size int) {
	return customSliceSerializer.Size([]int(v))
}

func (s customSliceMUS) Skip(r mus.Reader) (n int, err error) {
	return customSliceSerializer.Skip(r)
}

// -----------------------------------------------------------------------------

var CustomMapMUS = customMapMUS{}

type customMapMUS struct{}

var customMapSerializer = ord.NewValidMapSer(
	ord.String,
	ord.NewSliceSer(raw.Int), // elem:enc = raw
	mapopts.WithLenSer[string, []int](raw.Int),
	mapopts.WithKeyValidator[string, []int](common.ValidatorFn[string](validators.ValidateMapKey)),
)

func (s customMapMUS) Marshal(v CustomMap, w mus.Writer) (n int, err error) {
	return customMapSerializer.Marshal(map[string][]int(v), w)
}

func (s customMapMUS) Unmarshal(r mus.Reader) (v CustomMap, n int, err error) {
	v1, n, err := customMapSerializer.Unmarshal(r)
	v = CustomMap(v1)
	return
}

func (s customMapMUS) Size(v CustomMap) (size int) {
	return customMapSerializer.Size(map[string][]int(v))
}

func (s customMapMUS) Skip(r mus.Reader) (n int, err error) {
	return customMapSerializer.Skip(r)
}

// -----------------------------------------------------------------------------

var EmbeddedMUS = embeddedMUS{}

type embeddedMUS struct{}

func (s embeddedMUS) Marshal(v Embedded, w mus.Writer) (n int, err error) {
	return ord.Bool.Marshal(v.Bool, w)
}

func (s embeddedMUS) Unmarshal(r mus.Reader) (v Embedded, n int, err error) {
	v.Bool, n, err = ord.Bool.Unmarshal(r)
	return
}

func (s embeddedMUS) Size(v Embedded) (size int) {
	return ord.Bool.Size(v.Bool)
}

func (s embeddedMUS) Skip(r mus.Reader) (n int, err error) {
	return ord.Bool.Skip(r)
}

// -----------------------------------------------------------------------------

// MyInterface (Impl1, Impl2)
const (
	Impl1DTM common.DTM = 0x1
	Impl2DTM common.DTM = 0x2
)

var MyInterfaceMUS = myInterfaceMUS{}

type myInterfaceMUS struct{}

func (s myInterfaceMUS) Marshal(v MyInterface, w mus.Writer) (n int, err error) {
	switch v1 := v.(type) {
	case Impl1:
		n, err = varint.Uint64.Marshal(uint64(Impl1DTM), w)
		if err != nil {
			return
		}
		var n1 int
		n1, err = Impl1MUS.Marshal(v1, w)
		n += n1
	case Impl2:
		n, err = varint.Uint64.Marshal(uint64(Impl2DTM), w)
		if err != nil {
			return
		}
		var n1 int
		n1, err = Impl2MUS.Marshal(v1, w)
		n += n1
	default:
		panic("unknown implementation for MyInterface")
	}
	return
}

func (s myInterfaceMUS) Unmarshal(r mus.Reader) (v MyInterface, n int, err error) {
	var (
		dtm uint64
		n1  int
	)
	dtm, n, err = varint.Uint64.Unmarshal(r)
	if err != nil {
		return
	}
	switch common.DTM(dtm) {
	case Impl1DTM:
		var impl Impl1
		impl, n1, err = Impl1MUS.Unmarshal(r)
		v = impl
	case Impl2DTM:
		var impl Impl2
		impl, n1, err = Impl2MUS.Unmarshal(r)
		v = impl
	default:
		err = common.ErrUnknownDTM
	}
	n += n1
	return
}

func (s myInterfaceMUS) Size(v MyInterface) (size int) {
	switch v1 := v.(type) {
	case Impl1:
		size = varint.Uint64.Size(uint64(Impl1DTM))
		size += Impl1MUS.Size(v1)
	case Impl2:
		size = varint.Uint64.Size(uint64(Impl2DTM))
		size += Impl2MUS.Size(v1)
	default:
		panic("unknown implementation for MyInterface")
	}
	return
}

func (s myInterfaceMUS) Skip(r mus.Reader) (n int, err error) {
	var (
		dtm uint64
		n1  int
	)
	dtm, n, err = varint.Uint64.Unmarshal(r)
	if err != nil {
		return
	}
	switch common.DTM(dtm) {
	case Impl1DTM:
		n1, err = Impl1MUS.Skip(r)
	case Impl2DTM:
		n1, err = Impl2MUS.Skip(r)
	default:
		err = common.ErrUnknownDTM
	}
	n += n1
	return
}

// -----------------------------------------------------------------------------

var Impl1MUS = impl1MUS{}

type impl1MUS struct{}

func (s impl1MUS) Marshal(v Impl1, w mus.Writer) (n int, err error) {
	return varint.Int.Marshal(v.A, w)
}

func (s impl1MUS) Unmarshal(r mus.Reader) (v Impl1, n int, err error) {
	v.A, n, err = varint.Int.Unmarshal(r)
	return
}

func (s impl1MUS) Size(v Impl1) (size int) {
	return varint.Int.Size(v.A)
}

func (s impl1MUS) Skip(r mus.Reader) (n int, err error) {
	return varint.Int.Skip(r)
}

// -----------------------------------------------------------------------------

var Impl2MUS = impl2MUS{}

type impl2MUS struct{}

func (s impl2MUS) Marshal(v Impl2, w mus.Writer) (n int, err error) {
	return ord.String.Marshal(v.B, w)
}

func (s impl2MUS) Unmarshal(r mus.Reader) (v Impl2, n int, err error) {
	v.B, n, err = ord.String.Unmarshal(r)
	return
}

func (s impl2MUS) Size(v Impl2) (size int) {
	return ord.String.Size(v.B)
}

func (s impl2MUS) Skip(r mus.Reader) (n int, err error) {
	return ord.String.Skip(r)
}

// -----------------------------------------------------------------------------

type stringWithValidatorMUS struct {
	valVl common.Validator[string]
}

func (s stringWithValidatorMUS) Marshal(v string, w mus.Writer) (n int, err error) {
	return ord.String.Marshal(v, w)
}

func (s stringWithValidatorMUS) Unmarshal(r mus.Reader) (v string, n int, err error) {
	v, n, err = ord.String.Unmarshal(r)
	if err != nil {
		return
	}
	err = s.valVl.Validate(v)
	return
}

func (s stringWithValidatorMUS) Size(v string) (size int) {
	return ord.String.Size(v)
}

func (s stringWithValidatorMUS) Skip(r mus.Reader) (n int, err error) {
	return ord.String.Skip(r)
}
