// Code generated by the AI agent with mus-gen-skill-go. DO NOT EDIT.

package userhints

import (
	"testing"
	"time"

	"github.com/mus-format/mus-go/test"
)

func TestUserHints(t *testing.T) {
	// CustomName
	t.Run("CustomName", func(t *testing.T) {
		cases := []Name{1, 2, 3}
		test.Test(cases, CustomName, t)
		test.TestSkip(cases, CustomName, t)
	})

	// Skip
	t.Run("Skip", func(t *testing.T) {
		cases := []Skip{{num: 1}, {num: 2}}
		test.Test(cases, SkipMUS, t)
		test.TestSkip(cases, SkipMUS, t)
	})

	// Valid
	t.Run("Valid", func(t *testing.T) {
		cases := []Valid{{num: 1}, {num: 2}}
		test.Test(cases, ValidMUS, t)
		test.TestSkip(cases, ValidMUS, t)
		// Validation
		test.TestValidation(cases[0], ValidMUS, nil, t)
		test.TestValidation(Valid{num: 0}, ValidMUS, ErrZeroNum, t)
	})

	// ValidField
	t.Run("ValidField", func(t *testing.T) {
		cases := []ValidField{{num: 1, str: "valid"}, {num: 2, str: "valid2"}}
		test.Test(cases, ValidFieldMUS, t)
		test.TestSkip(cases, ValidFieldMUS, t)
		// Validation
		test.TestValidation(cases[0], ValidFieldMUS, nil, t)
		test.TestValidation(ValidField{num: -1, str: "v"}, ValidFieldMUS, ErrNegativeNum, t)
		test.TestValidation(ValidField{num: 1, str: ""}, ValidFieldMUS, ErrEmptyStr, t)
	})

	// Time
	t.Run("Time", func(t *testing.T) {
		now := time.Now().Truncate(time.Nanosecond)
		cases := []Time{Time(now)}
		test.Test(cases, TimeMUS, t)
		test.TestSkip(cases, TimeMUS, t)
	})

	// DefMap
	t.Run("DefMap", func(t *testing.T) {
		cases := []DefMap{{"k1": 1, "k2": 2}, {}}
		test.Test(cases, DefMapMUS, t)
		test.TestSkip(cases, DefMapMUS, t)
		// Validation
		test.TestValidation(cases[0], DefMapMUS, nil, t)
		test.TestValidation(DefMap{"": 1}, DefMapMUS, ErrEmptyKey, t)
		test.TestValidation(DefMap{"k": -1}, DefMapMUS, ErrNegativeValue, t)
	})

	// DefSlice
	t.Run("DefSlice", func(t *testing.T) {
		cases := []DefSlice{{1, 2, 3}, {}}
		test.Test(cases, DefSliceMUS, t)
		test.TestSkip(cases, DefSliceMUS, t)
		// Validation
		test.TestValidation(cases[0], DefSliceMUS, nil, t)
		test.TestValidation(DefSlice{-1}, DefSliceMUS, ErrNegativeElement, t)
	})

	// DefArray
	t.Run("DefArray", func(t *testing.T) {
		cases := []DefArray{{1, 2, 3}, {0, 0, 0}}
		test.Test(cases, DefArrayMUS, t)
		test.TestSkip(cases, DefArrayMUS, t)
		// Validation
		test.TestValidation(cases[0], DefArrayMUS, nil, t)
		test.TestValidation(DefArray{-1, 0, 0}, DefArrayMUS, ErrNegativeElement, t)
	})

	// Nested
	t.Run("Nested", func(t *testing.T) {
		cases := []Nested{{"k1": {{1, 2, 3}, {4, 5, 6}}, "k2": {}}, {}}
		test.Test(cases, NestedMUS, t)
		test.TestSkip(cases, NestedMUS, t)
		// Validation
		test.TestValidation(cases[0], NestedMUS, nil, t)
		test.TestValidation(Nested{"": {}}, NestedMUS, ErrEmptyKey, t)
		test.TestValidation(Nested{"k": {{1, 2, -1}}}, NestedMUS, ErrNegativeElement, t)
	})
}
