// Code generated by the AI agent with mus-skill-go. DO NOT EDIT.

package userhints

import (
	"time"

	"github.com/mus-format/common-go"
	arropts "github.com/mus-format/mus-go/options/array"
	mapopts "github.com/mus-format/mus-go/options/map"
	slopts "github.com/mus-format/mus-go/options/slice"
	stropts "github.com/mus-format/mus-go/options/string"
	"github.com/mus-format/mus-go/ord"
	"github.com/mus-format/mus-go/raw"
	"github.com/mus-format/mus-go/unsafe"
	"github.com/mus-format/mus-go/varint"
)

// Name (mus:name = CustomName)
var CustomName = nameMUS{}

type nameMUS struct{}

func (s nameMUS) Marshal(v Name, bs []byte) (n int) {
	return varint.Int.Marshal(int(v), bs)
}

func (s nameMUS) Unmarshal(bs []byte) (v Name, n int, err error) {
	v1, n, err := varint.Int.Unmarshal(bs)
	v = Name(v1)
	return
}

func (s nameMUS) Size(v Name) (size int) {
	return varint.Int.Size(int(v))
}

func (s nameMUS) Skip(bs []byte) (n int, err error) {
	return varint.Int.Skip(bs)
}

// -----------------------------------------------------------------------------

// Skip (mus:skip = secret)
var SkipMUS = skipMUS{}

type skipMUS struct{}

func (s skipMUS) Marshal(v Skip, bs []byte) (n int) {
	return varint.Int.Marshal(v.num, bs)
}

func (s skipMUS) Unmarshal(bs []byte) (v Skip, n int, err error) {
	v.num, n, err = varint.Int.Unmarshal(bs)
	return
}

func (s skipMUS) Size(v Skip) (size int) {
	return varint.Int.Size(v.num)
}

func (s skipMUS) Skip(bs []byte) (n int, err error) {
	return varint.Int.Skip(bs)
}

// -----------------------------------------------------------------------------

// Valid (mus:vl = ValidateStruct)
var ValidMUS = validMUS{}

type validMUS struct{}

func (s validMUS) Marshal(v Valid, bs []byte) (n int) {
	return varint.Int.Marshal(v.num, bs)
}

func (s validMUS) Unmarshal(bs []byte) (v Valid, n int, err error) {
	v.num, n, err = varint.Int.Unmarshal(bs)
	if err != nil {
		return
	}
	err = ValidateStruct(v)
	return
}

func (s validMUS) Size(v Valid) (size int) {
	return varint.Int.Size(v.num)
}

func (s validMUS) Skip(bs []byte) (n int, err error) {
	return varint.Int.Skip(bs)
}

// -----------------------------------------------------------------------------

// ValidField
var ValidFieldMUS = validFieldMUS{}

type validFieldMUS struct{}

func (s validFieldMUS) Marshal(v ValidField, bs []byte) (n int) {
	n = varint.Int.Marshal(v.num, bs)
	n += ord.String.Marshal(v.str, bs[n:])
	return
}

func (s validFieldMUS) Unmarshal(bs []byte) (v ValidField, n int, err error) {
	var n1 int
	v.num, n, err = varint.Int.Unmarshal(bs)
	if err != nil {
		return
	}
	if err = ValidateNum(v.num); err != nil {
		return
	}
	v.str, n1, err = ord.String.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	if err = ValidateStr(v.str); err != nil {
		return
	}
	return
}

func (s validFieldMUS) Size(v ValidField) (size int) {
	size = varint.Int.Size(v.num)
	size += ord.String.Size(v.str)
	return
}

func (s validFieldMUS) Skip(bs []byte) (n int, err error) {
	var n1 int
	n, err = varint.Int.Skip(bs)
	if err != nil {
		return
	}
	n1, err = ord.String.Skip(bs[n:])
	n += n1
	return
}

// -----------------------------------------------------------------------------

// Time (mus:time_unit = nano_utc)
var TimeMUS = timeMUS{}

type timeMUS struct{}

func (s timeMUS) Marshal(v Time, bs []byte) (n int) {
	return raw.TimeUnixNano.Marshal(time.Time(v), bs)
}

func (s timeMUS) Unmarshal(bs []byte) (v Time, n int, err error) {
	v1, n, err := raw.TimeUnixNano.Unmarshal(bs)
	v = Time(v1)
	return
}

func (s timeMUS) Size(v Time) (size int) {
	return raw.TimeUnixNano.Size(time.Time(v))
}

func (s timeMUS) Skip(bs []byte) (n int, err error) {
	return raw.TimeUnixNano.Skip(bs)
}

// -----------------------------------------------------------------------------

// DefMap (mus:lenSer = raw.Int, mus:lenVl = ValidateLength, mus:keyVl = ValidateKey, mus:valVl = ValidateValue)
var DefMapMUS = defMapMUS{}

type defMapMUS struct{}

var defMapSerializer = ord.NewValidMapSer(
	ord.String,
	varint.Int,
	mapopts.WithLenSer[string, int](raw.Int),
	mapopts.WithLenValidator[string, int](common.ValidatorFn[int](ValidateLength)),
	mapopts.WithKeyValidator[string, int](common.ValidatorFn[string](ValidateKey)),
	mapopts.WithValueValidator[string, int](common.ValidatorFn[int](ValidateValue)),
)

func (s defMapMUS) Marshal(v DefMap, bs []byte) (n int) {
	return defMapSerializer.Marshal(map[string]int(v), bs)
}

func (s defMapMUS) Unmarshal(bs []byte) (v DefMap, n int, err error) {
	v1, n, err := defMapSerializer.Unmarshal(bs)
	v = DefMap(v1)
	return
}

func (s defMapMUS) Size(v DefMap) (size int) {
	return defMapSerializer.Size(map[string]int(v))
}

func (s defMapMUS) Skip(bs []byte) (n int, err error) {
	return defMapSerializer.Skip(bs)
}

// -----------------------------------------------------------------------------

// DefSlice (mus:lenSer = raw.Int, mus:lenVl = ValidateLength, mus:elemVl = ValidateElement)
var DefSliceMUS = defSliceMUS{}

type defSliceMUS struct{}

var defSliceSerializer = ord.NewValidSliceSer(
	varint.Int,
	slopts.WithLenSer[int](raw.Int),
	slopts.WithLenValidator[int](common.ValidatorFn[int](ValidateLength)),
	slopts.WithElemValidator[int](common.ValidatorFn[int](ValidateElement)),
)

func (s defSliceMUS) Marshal(v DefSlice, bs []byte) (n int) {
	return defSliceSerializer.Marshal([]int(v), bs)
}

func (s defSliceMUS) Unmarshal(bs []byte) (v DefSlice, n int, err error) {
	v1, n, err := defSliceSerializer.Unmarshal(bs)
	v = DefSlice(v1)
	return
}

func (s defSliceMUS) Size(v DefSlice) (size int) {
	return defSliceSerializer.Size([]int(v))
}

func (s defSliceMUS) Skip(bs []byte) (n int, err error) {
	return defSliceSerializer.Skip(bs)
}

// -----------------------------------------------------------------------------

// DefArray (mus:lenSer = raw.Int, mus:elemVl = ValidateElement)
var DefArrayMUS = defArrayMUS{}

type defArrayMUS struct{}

var defArraySerializer = unsafe.NewValidArraySer[[3]int, int](
	varint.Int,
	arropts.WithLenSer[int](raw.Int),
	arropts.WithElemValidator[int](common.ValidatorFn[int](ValidateElement)),
)

func (s defArrayMUS) Marshal(v DefArray, bs []byte) (n int) {
	return defArraySerializer.Marshal([3]int(v), bs)
}

func (s defArrayMUS) Unmarshal(bs []byte) (v DefArray, n int, err error) {
	v1, n, err := defArraySerializer.Unmarshal(bs)
	v = DefArray(v1)
	return
}

func (s defArrayMUS) Size(v DefArray) (size int) {
	return defArraySerializer.Size([3]int(v))
}

func (s defArrayMUS) Skip(bs []byte) (n int, err error) {
	return defArraySerializer.Skip(bs)
}

// -----------------------------------------------------------------------------

// Nested map[string][][3]int with many hints
var NestedMUS = nestedMUS{}

type nestedMUS struct{}

var (
	// val:elem:elem (enc = raw)
	valElemElemSer = raw.Int

	// val:elem ([3]int, lenSer = varint.Int, elemVl = ValidateElement)
	valElemSer = unsafe.NewValidArraySer[[3]int, int](
		valElemElemSer,
		arropts.WithLenSer[int](varint.Int),
		arropts.WithElemValidator[int](common.ValidatorFn[int](ValidateElement)),
	)

	// val ([][3]int, lenSer = raw.Int, lenVl = ValidateLength)
	valSer = ord.NewValidSliceSer(
		valElemSer,
		slopts.WithLenSer[[3]int](raw.Int),
		slopts.WithLenValidator[[3]int](common.ValidatorFn[int](ValidateLength)),
	)

	// key (string, lenSer = varint.Int, lenVl = ValidateLength)
	keySer = ord.NewValidStringSer(
		stropts.WithLenSer(varint.Int),
		stropts.WithLenValidator(common.ValidatorFn[int](ValidateLength)),
	)

	// nestedSerializer (map, lenSer = raw.Int, lenVl = ValidateLength, keyVl = ValidateKey)
	nestedSerializer = ord.NewValidMapSer(
		keySer,
		valSer,
		mapopts.WithLenSer[string, [][3]int](raw.Int),
		mapopts.WithLenValidator[string, [][3]int](common.ValidatorFn[int](ValidateLength)),
		mapopts.WithKeyValidator[string, [][3]int](common.ValidatorFn[string](ValidateKey)),
	)
)

func (s nestedMUS) Marshal(v Nested, bs []byte) (n int) {
	return nestedSerializer.Marshal(map[string][][3]int(v), bs)
}

func (s nestedMUS) Unmarshal(bs []byte) (v Nested, n int, err error) {
	v1, n, err := nestedSerializer.Unmarshal(bs)
	v = Nested(v1)
	return
}

func (s nestedMUS) Size(v Nested) (size int) {
	return nestedSerializer.Size(map[string][][3]int(v))
}

func (s nestedMUS) Skip(bs []byte) (n int, err error) {
	return nestedSerializer.Skip(bs)
}
