// Code generated by the AI agent with mus-skill-go. DO NOT EDIT.

package sers

import (
	"image"

	"github.com/mus-format/mus-go/ord"
	"github.com/mus-format/mus-go/varint"
	"github.com/mus-format/mus-skill-go/test/mus-go/complex/sub1"
	"github.com/mus-format/mus-skill-go/test/mus-go/complex/sub2"
)

var Bar1 = bar1{}

type bar1 struct{}

func (s bar1) Marshal(v sub1.Bar, bs []byte) (n int) {
	return varint.Int.Marshal(v.Int, bs)
}

func (s bar1) Unmarshal(bs []byte) (v sub1.Bar, n int, err error) {
	v.Int, n, err = varint.Int.Unmarshal(bs)
	return
}

func (s bar1) Size(v sub1.Bar) (size int) {
	return varint.Int.Size(v.Int)
}

func (s bar1) Skip(bs []byte) (n int, err error) {
	return varint.Int.Skip(bs)
}

// -----------------------------------------------------------------------------

var Bar2 = bar2{}

type bar2 struct{}

func (s bar2) Marshal(v sub2.Bar, bs []byte) (n int) {
	return ord.String.Marshal(v.Str, bs)
}

func (s bar2) Unmarshal(bs []byte) (v sub2.Bar, n int, err error) {
	v.Str, n, err = ord.String.Unmarshal(bs)
	return
}

func (s bar2) Size(v sub2.Bar) (size int) {
	return ord.String.Size(v.Str)
}

func (s bar2) Skip(bs []byte) (n int, err error) {
	return ord.String.Skip(bs)
}

// -----------------------------------------------------------------------------

var PointMUS = pointMUS{}

type pointMUS struct{}

func (s pointMUS) Marshal(v image.Point, bs []byte) (n int) {
	n = varint.Int.Marshal(v.X, bs)
	n += varint.Int.Marshal(v.Y, bs[n:])
	return
}

func (s pointMUS) Unmarshal(bs []byte) (v image.Point, n int, err error) {
	var n1 int
	v.X, n, err = varint.Int.Unmarshal(bs)
	if err != nil {
		return
	}
	v.Y, n1, err = varint.Int.Unmarshal(bs[n:])
	n += n1
	return
}

func (s pointMUS) Size(v image.Point) (size int) {
	size = varint.Int.Size(v.X)
	size += varint.Int.Size(v.Y)
	return
}

func (s pointMUS) Skip(bs []byte) (n int, err error) {
	var n1 int
	n, err = varint.Int.Skip(bs)
	if err != nil {
		return
	}
	n1, err = varint.Int.Skip(bs[n:])
	n += n1
	return
}
