// Code generated by the AI agent with mus-gen-skill-go. DO NOT EDIT.

package crossmodule

import (
	"image"

	"github.com/mus-format/mus-go/varint"
)

var FooMUS = fooMUS{}

type fooMUS struct{}

func (s fooMUS) Marshal(v Foo, bs []byte) (n int) {
	return PointMUS.Marshal(v.point, bs)
}

func (s fooMUS) Unmarshal(bs []byte) (v Foo, n int, err error) {
	v.point, n, err = PointMUS.Unmarshal(bs)
	return
}

func (s fooMUS) Size(v Foo) (size int) {
	return PointMUS.Size(v.point)
}

func (s fooMUS) Skip(bs []byte) (n int, err error) {
	return PointMUS.Skip(bs)
}

// -----------------------------------------------------------------------------

var PointMUS = pointMUS{}

type pointMUS struct{}

func (s pointMUS) Marshal(v image.Point, bs []byte) (n int) {
	n = varint.Int.Marshal(v.X, bs)
	n += varint.Int.Marshal(v.Y, bs[n:])
	return
}

func (s pointMUS) Unmarshal(bs []byte) (v image.Point, n int, err error) {
	var n1 int
	v.X, n, err = varint.Int.Unmarshal(bs)
	if err != nil {
		return
	}
	v.Y, n1, err = varint.Int.Unmarshal(bs[n:])
	n += n1
	return
}

func (s pointMUS) Size(v image.Point) (size int) {
	size = varint.Int.Size(v.X)
	size += varint.Int.Size(v.Y)
	return
}

func (s pointMUS) Skip(bs []byte) (n int, err error) {
	var n1 int
	n, err = varint.Int.Skip(bs)
	if err != nil {
		return
	}
	n1, err = varint.Int.Skip(bs[n:])
	n += n1
	return
}
