// Code generated by the AI agent with mus-skill-go. DO NOT EDIT.

package custommode

import (
	"github.com/mus-format/mus-go/raw"
	"github.com/mus-format/mus-go/unsafe"
)

var FooMUS = fooMUS{}

type fooMUS struct{}

func (s fooMUS) Marshal(v Foo, bs []byte) (n int) {
	n = raw.Int.Marshal(v.num, bs)
	n += unsafe.String.Marshal(v.str, bs[n:])
	return
}

func (s fooMUS) Unmarshal(bs []byte) (v Foo, n int, err error) {
	var n1 int
	v.num, n, err = raw.Int.Unmarshal(bs)
	if err != nil {
		return
	}
	v.str, n1, err = unsafe.String.Unmarshal(bs[n:])
	n += n1
	return
}

func (s fooMUS) Size(v Foo) (size int) {
	size = raw.Int.Size(v.num)
	size += unsafe.String.Size(v.str)
	return
}

func (s fooMUS) Skip(bs []byte) (n int, err error) {
	var n1 int
	n, err = raw.Int.Skip(bs)
	if err != nil {
		return
	}
	n1, err = unsafe.String.Skip(bs[n:])
	n += n1
	return
}
