// Code generated by the AI agent with mus-gen-skill-go. DO NOT EDIT.

package sub

import (
	userhints "github.com/mus-format/mus-gen-skill-go/test/mus-stream-go/user_hints"
	"github.com/mus-format/mus-stream-go"
	"github.com/mus-format/mus-stream-go/varint"
)

var CrossPackageMUS = crossPackageMUS{}

type crossPackageMUS struct{}

func (s crossPackageMUS) Marshal(v userhints.CrossPackage, w mus.Writer) (n int, err error) {
	return varint.Int.Marshal(int(v), w)
}

func (s crossPackageMUS) Unmarshal(r mus.Reader) (v userhints.CrossPackage, n int, err error) {
	v1, n, err := varint.Int.Unmarshal(r)
	v = userhints.CrossPackage(v1)
	return
}

func (s crossPackageMUS) Size(v userhints.CrossPackage) (size int) {
	return varint.Int.Size(int(v))
}

func (s crossPackageMUS) Skip(r mus.Reader) (n int, err error) {
	return varint.Int.Skip(r)
}
