// Code generated by AI agent with mus-skill. DO NOT EDIT.

package unsafe

import (
	"github.com/mus-format/mus-go/ord"
	"github.com/mus-format/mus-go/unsafe"
	"github.com/mus-format/mus-skill-go/test/mode"
)

// FullDefinedMUS
var FullDefinedMUS = fullDefinedMUS{}

type fullDefinedMUS struct{}

func (s fullDefinedMUS) Marshal(v mode.FullDefined, bs []byte) (n int) {
	return unsafe.Int.Marshal(int(v), bs)
}

func (s fullDefinedMUS) Unmarshal(bs []byte) (v mode.FullDefined, n int, err error) {
	tmp, n, err := unsafe.Int.Unmarshal(bs)
	if err != nil {
		return
	}
	v = mode.FullDefined(tmp)
	return
}

func (s fullDefinedMUS) Size(v mode.FullDefined) (size int) {
	return unsafe.Int.Size(int(v))
}

func (s fullDefinedMUS) Skip(bs []byte) (n int, err error) {
	return unsafe.Int.Skip(bs)
}

// FullInterfaceImplMUS
var FullInterfaceImplMUS = fullInterfaceImplMUS{}

type fullInterfaceImplMUS struct{}

func (s fullInterfaceImplMUS) Marshal(v mode.FullInterfaceImpl, bs []byte) (n int) {
	return unsafe.String.Marshal(string(v), bs)
}

func (s fullInterfaceImplMUS) Unmarshal(bs []byte) (v mode.FullInterfaceImpl, n int, err error) {
	tmp, n, err := unsafe.String.Unmarshal(bs)
	if err != nil {
		return
	}
	v = mode.FullInterfaceImpl(tmp)
	return
}

func (s fullInterfaceImplMUS) Size(v mode.FullInterfaceImpl) (size int) {
	return unsafe.String.Size(string(v))
}

func (s fullInterfaceImplMUS) Skip(bs []byte) (n int, err error) {
	return unsafe.String.Skip(bs)
}

// Anonymous serializers
var (
	ptrgyz6lfcPDFFKs3VdEsnvGQΞΞ   = ord.NewPtrSer(unsafe.Int)
	arraygyz6lfcPDFFKs3VdEsnvGQΞΞ = unsafe.NewArraySer[[10]int](unsafe.Int)
	slicegyz6lfcPDFFKs3VdEsnvGQΞΞ = ord.NewSliceSer(unsafe.Int)
	mapΣQsQeU4uG1tQawWZrpKKAgΞΞ   = ord.NewMapSer(unsafe.String, unsafe.Int)
)

// FullStructMUS
var FullStructMUS = fullStructMUS{}

type fullStructMUS struct{}

func (s fullStructMUS) Marshal(v mode.FullStruct, bs []byte) (n int) {
	n = unsafe.Int.Marshal(v.Int, bs)
	n += unsafe.Int64.Marshal(v.Int64, bs[n:])
	n += unsafe.Int32.Marshal(v.Int32, bs[n:])
	n += unsafe.Int16.Marshal(v.Int16, bs[n:])
	n += unsafe.Int8.Marshal(v.Int8, bs[n:])
	n += unsafe.Uint.Marshal(v.Uint, bs[n:])
	n += unsafe.Uint64.Marshal(v.Uint64, bs[n:])
	n += unsafe.Uint32.Marshal(v.Uint32, bs[n:])
	n += unsafe.Uint16.Marshal(v.Uint16, bs[n:])
	n += unsafe.Uint8.Marshal(v.Uint8, bs[n:])
	n += unsafe.Float64.Marshal(v.Float64, bs[n:])
	n += unsafe.Float32.Marshal(v.Float32, bs[n:])
	n += unsafe.Uint8.Marshal(v.Byte, bs[n:])
	n += unsafe.Bool.Marshal(v.Bool, bs[n:])
	n += unsafe.String.Marshal(v.Str, bs[n:])
	n += unsafe.ByteSlice.Marshal(v.ByteSlice, bs[n:])
	n += unsafe.ByteSlice.Marshal(v.Uint8Slice, bs[n:])
	n += unsafe.TimeUnixUTC.Marshal(v.Time, bs[n:])
	n += ptrgyz6lfcPDFFKs3VdEsnvGQΞΞ.Marshal(v.PtrInt, bs[n:])
	n += arraygyz6lfcPDFFKs3VdEsnvGQΞΞ.Marshal(v.ArrayInt, bs[n:])
	n += slicegyz6lfcPDFFKs3VdEsnvGQΞΞ.Marshal(v.SliceInt, bs[n:])
	n += mapΣQsQeU4uG1tQawWZrpKKAgΞΞ.Marshal(v.MapStrInt, bs[n:])
	n += FullDefinedMUS.Marshal(v.Defined, bs[n:])
	return n
}

func (s fullStructMUS) Unmarshal(bs []byte) (v mode.FullStruct, n int, err error) {
	var n1 int
	v.Int, n1, err = unsafe.Int.Unmarshal(bs)
	n += n1
	if err != nil {
		return
	}
	v.Int64, n1, err = unsafe.Int64.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Int32, n1, err = unsafe.Int32.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Int16, n1, err = unsafe.Int16.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Int8, n1, err = unsafe.Int8.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Uint, n1, err = unsafe.Uint.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Uint64, n1, err = unsafe.Uint64.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Uint32, n1, err = unsafe.Uint32.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Uint16, n1, err = unsafe.Uint16.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Uint8, n1, err = unsafe.Uint8.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Float64, n1, err = unsafe.Float64.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Float32, n1, err = unsafe.Float32.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Byte, n1, err = unsafe.Uint8.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Bool, n1, err = unsafe.Bool.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Str, n1, err = unsafe.String.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.ByteSlice, n1, err = unsafe.ByteSlice.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Uint8Slice, n1, err = unsafe.ByteSlice.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Time, n1, err = unsafe.TimeUnixUTC.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.PtrInt, n1, err = ptrgyz6lfcPDFFKs3VdEsnvGQΞΞ.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.ArrayInt, n1, err = arraygyz6lfcPDFFKs3VdEsnvGQΞΞ.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.SliceInt, n1, err = slicegyz6lfcPDFFKs3VdEsnvGQΞΞ.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.MapStrInt, n1, err = mapΣQsQeU4uG1tQawWZrpKKAgΞΞ.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Defined, n1, err = FullDefinedMUS.Unmarshal(bs[n:])
	n += n1
	return
}

func (s fullStructMUS) Size(v mode.FullStruct) (size int) {
	size = unsafe.Int.Size(v.Int)
	size += unsafe.Int64.Size(v.Int64)
	size += unsafe.Int32.Size(v.Int32)
	size += unsafe.Int16.Size(v.Int16)
	size += unsafe.Int8.Size(v.Int8)
	size += unsafe.Uint.Size(v.Uint)
	size += unsafe.Uint64.Size(v.Uint64)
	size += unsafe.Uint32.Size(v.Uint32)
	size += unsafe.Uint16.Size(v.Uint16)
	size += unsafe.Uint8.Size(v.Uint8)
	size += unsafe.Float64.Size(v.Float64)
	size += unsafe.Float32.Size(v.Float32)
	size += unsafe.Uint8.Size(v.Byte)
	size += unsafe.Bool.Size(v.Bool)
	size += unsafe.String.Size(v.Str)
	size += unsafe.ByteSlice.Size(v.ByteSlice)
	size += unsafe.ByteSlice.Size(v.Uint8Slice)
	size += unsafe.TimeUnixUTC.Size(v.Time)
	size += ptrgyz6lfcPDFFKs3VdEsnvGQΞΞ.Size(v.PtrInt)
	size += arraygyz6lfcPDFFKs3VdEsnvGQΞΞ.Size(v.ArrayInt)
	size += slicegyz6lfcPDFFKs3VdEsnvGQΞΞ.Size(v.SliceInt)
	size += mapΣQsQeU4uG1tQawWZrpKKAgΞΞ.Size(v.MapStrInt)
	size += FullDefinedMUS.Size(v.Defined)
	return size
}

func (s fullStructMUS) Skip(bs []byte) (n int, err error) {
	var n1 int
	n1, err = unsafe.Int.Skip(bs)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Int64.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Int32.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Int16.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Int8.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint64.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint32.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint16.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint8.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Float64.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Float32.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint8.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Bool.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.String.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.ByteSlice.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.ByteSlice.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.TimeUnixUTC.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = ptrgyz6lfcPDFFKs3VdEsnvGQΞΞ.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = arraygyz6lfcPDFFKs3VdEsnvGQΞΞ.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = slicegyz6lfcPDFFKs3VdEsnvGQΞΞ.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = mapΣQsQeU4uG1tQawWZrpKKAgΞΞ.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = FullDefinedMUS.Skip(bs[n:])
	n += n1
	return
}
