// Code generated by AI agent with mus-skill. DO NOT EDIT.

package unsafe

import (
	"testing"
	"time"

	"github.com/mus-format/mus-go/test"
	"github.com/mus-format/mus-skill-go/test/mode"
)

func TestFullStruct(t *testing.T) {
	var (
		ser   = FullStructMUS
		n     = 10
		ptr   = &n
		cases = []mode.FullStruct{
			{
				Int:        1,
				Int64:      2,
				Int32:      3,
				Int16:      4,
				Int8:       5,
				Uint:       6,
				Uint64:     7,
				Uint32:     8,
				Uint16:     9,
				Uint8:      10,
				Float64:    11.1,
				Float32:    12.2,
				Byte:       13,
				Bool:       true,
				Str:        "hello",
				ByteSlice:  []byte{1, 2, 3},
				Uint8Slice: []uint8{4, 5, 6},
				Time:       time.Now().Truncate(time.Second).UTC(),
				PtrInt:     ptr,
				ArrayInt:   [10]int{1, 2, 3, 4, 5, 6, 7, 8, 9, 10},
				SliceInt:   []int{1, 2, 3},
				MapStrInt:  map[string]int{"a": 1, "b": 2},
				Defined:    mode.FullDefined(100),
			},
			{
				ByteSlice:  []byte{},
				Uint8Slice: []uint8{},
				SliceInt:   []int{},
				MapStrInt:  map[string]int{},
			},
		}
	)
	test.Test(cases, ser, t)
	test.TestSkip(cases, ser, t)
}

func TestFullDefined(t *testing.T) {
	var (
		ser   = FullDefinedMUS
		cases = []mode.FullDefined{0, 1, -1, 100}
	)
	test.Test(cases, ser, t)
	test.TestSkip(cases, ser, t)
}

func TestFullInterfaceImpl(t *testing.T) {
	var (
		ser   = FullInterfaceImplMUS
		cases = []mode.FullInterfaceImpl{"", "hi"}
	)
	test.Test(cases, ser, t)
	test.TestSkip(cases, ser, t)
}
