// Code generated by the AI agent with mus-gen-skill-go. DO NOT EDIT.

package bar

import (
	"github.com/mus-format/mus-stream-go"
	"github.com/mus-format/mus-stream-go/ord"
)

var BarMUS = barMUS{}

type barMUS struct{}

func (s barMUS) Marshal(v Bar, w mus.Writer) (n int, err error) {
	return ord.ByteSlice.Marshal(v.Sl, w)
}

func (s barMUS) Unmarshal(r mus.Reader) (v Bar, n int, err error) {
	v.Sl, n, err = ord.ByteSlice.Unmarshal(r)
	return
}

func (s barMUS) Size(v Bar) (size int) {
	return ord.ByteSlice.Size(v.Sl)
}

func (s barMUS) Skip(r mus.Reader) (n int, err error) {
	return ord.ByteSlice.Skip(r)
}
