// Code generated by the AI agent with mus-skill-go. DO NOT EDIT.

package crossmodule

import (
	"image"
	"testing"

	"github.com/mus-format/mus-stream-go/test"
)

func TestFoo(t *testing.T) {
	cases := []Foo{
		{point: image.Point{X: 1, Y: 2}},
		{point: image.Point{X: -1, Y: -2}},
		{point: image.Point{X: 0, Y: 0}},
	}
	test.Test(cases, FooMUS, t)
	test.TestSkip(cases, FooMUS, t)
}
