// Code generated by the AI agent with mus-skill-go. DO NOT EDIT.

package crossmodule

import (
	"image"

	"github.com/mus-format/mus-stream-go"
	"github.com/mus-format/mus-stream-go/varint"
)

var FooMUS = fooMUS{}

type fooMUS struct{}

func (s fooMUS) Marshal(v Foo, w mus.Writer) (n int, err error) {
	return PointMUS.Marshal(v.point, w)
}

func (s fooMUS) Unmarshal(r mus.Reader) (v Foo, n int, err error) {
	v.point, n, err = PointMUS.Unmarshal(r)
	return
}

func (s fooMUS) Size(v Foo) (size int) {
	return PointMUS.Size(v.point)
}

func (s fooMUS) Skip(r mus.Reader) (n int, err error) {
	return PointMUS.Skip(r)
}

// -----------------------------------------------------------------------------

var PointMUS = pointMUS{}

type pointMUS struct{}

func (s pointMUS) Marshal(v image.Point, w mus.Writer) (n int, err error) {
	n, err = varint.Int.Marshal(v.X, w)
	if err != nil {
		return
	}
	var n1 int
	n1, err = varint.Int.Marshal(v.Y, w)
	n += n1
	return
}

func (s pointMUS) Unmarshal(r mus.Reader) (v image.Point, n int, err error) {
	var n1 int
	v.X, n, err = varint.Int.Unmarshal(r)
	if err != nil {
		return
	}
	v.Y, n1, err = varint.Int.Unmarshal(r)
	n += n1
	return
}

func (s pointMUS) Size(v image.Point) (size int) {
	size = varint.Int.Size(v.X)
	size += varint.Int.Size(v.Y)
	return
}

func (s pointMUS) Skip(r mus.Reader) (n int, err error) {
	var n1 int
	n, err = varint.Int.Skip(r)
	if err != nil {
		return
	}
	n1, err = varint.Int.Skip(r)
	n += n1
	return
}
