// Code generated by the AI agent with mus-skill-go. DO NOT EDIT.

package structure

import (
	"testing"

	"github.com/mus-format/mus-go/test"
)

func TestFoo(t *testing.T) {
	cases := []Foo{
		{
			num: 1,
			str: "struct",
			sl:  []uint8{1, 2, 3},
			mp:  map[float64]int32{1.1: 1, 2.2: 2},
		},
		{
			sl: []uint8{},
			mp: map[float64]int32{},
		},
	}
	test.Test(cases, FooMUS, t)
	test.TestSkip(cases, FooMUS, t)
}
