// Code generated by the AI agent with mus-gen-skill-go. DO NOT EDIT.

package structure

import (
	"github.com/mus-format/mus-go/ord"
	"github.com/mus-format/mus-go/varint"
)

var FooMUS = fooMUS{}

type fooMUS struct{}

func (s fooMUS) Marshal(v Foo, bs []byte) (n int) {
	n = varint.Int8.Marshal(v.num, bs)
	n += ord.String.Marshal(v.str, bs[n:])
	n += ord.ByteSlice.Marshal(v.sl, bs[n:])
	n += ord.NewMapSer(varint.Float64, varint.Int32).Marshal(v.mp, bs[n:])
	return
}

func (s fooMUS) Unmarshal(bs []byte) (v Foo, n int, err error) {
	var n1 int
	v.num, n, err = varint.Int8.Unmarshal(bs)
	if err != nil {
		return
	}
	v.str, n1, err = ord.String.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.sl, n1, err = ord.ByteSlice.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.mp, n1, err = ord.NewMapSer(varint.Float64, varint.Int32).Unmarshal(bs[n:])
	n += n1
	return
}

func (s fooMUS) Size(v Foo) (size int) {
	size = varint.Int8.Size(v.num)
	size += ord.String.Size(v.str)
	size += ord.ByteSlice.Size(v.sl)
	size += ord.NewMapSer(varint.Float64, varint.Int32).Size(v.mp)
	return
}

func (s fooMUS) Skip(bs []byte) (n int, err error) {
	var n1 int
	n, err = varint.Int8.Skip(bs)
	if err != nil {
		return
	}
	n1, err = ord.String.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.ByteSlice.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.NewMapSer(varint.Float64, varint.Int32).Skip(bs[n:])
	n += n1
	return
}
