// Code generated by the AI agent with mus-gen-skill-go. DO NOT EDIT.

package multipackage

import (
	"testing"

	bar "github.com/mus-format/mus-gen-skill-go/test/mus-stream-go/multi-package/sub"
	"github.com/mus-format/mus-stream-go/test"
)

func TestMultiPackage(t *testing.T) {
	// Foo
	t.Run("Foo", func(t *testing.T) {
		cases := []Foo{
			{Bar: bar.Bar{Sl: []byte{1, 2, 3}}},
			{Bar: bar.Bar{Sl: []byte{}}},
		}
		test.Test(cases, FooMUS, t)
		test.TestSkip(cases, FooMUS, t)
	})

	// Zoo
	t.Run("Zoo", func(t *testing.T) {
		cases := []Zoo{
			Zoo(bar.Bar{Sl: []byte{4, 5, 6}}),
			Zoo(bar.Bar{Sl: []byte{}}),
		}
		test.Test(cases, ZooMUS, t)
		test.TestSkip(cases, ZooMUS, t)
	})
}
