// Code generated by the AI agent with mus-gen-skill-go. DO NOT EDIT.

package multipackage

import (
	bar "github.com/mus-format/mus-gen-skill-go/test/mus-stream-go/multi-package/sub"
	"github.com/mus-format/mus-stream-go"
)

var FooMUS = fooMUS{}

type fooMUS struct{}

func (s fooMUS) Marshal(v Foo, w mus.Writer) (n int, err error) {
	return bar.BarMUS.Marshal(v.Bar, w)
}

func (s fooMUS) Unmarshal(r mus.Reader) (v Foo, n int, err error) {
	v.Bar, n, err = bar.BarMUS.Unmarshal(r)
	return
}

func (s fooMUS) Size(v Foo) (size int) {
	return bar.BarMUS.Size(v.Bar)
}

func (s fooMUS) Skip(r mus.Reader) (n int, err error) {
	return bar.BarMUS.Skip(r)
}

// -----------------------------------------------------------------------------

var ZooMUS = zooMUS{}

type zooMUS struct{}

func (s zooMUS) Marshal(v Zoo, w mus.Writer) (n int, err error) {
	return bar.BarMUS.Marshal(bar.Bar(v), w)
}

func (s zooMUS) Unmarshal(r mus.Reader) (v Zoo, n int, err error) {
	v1, n, err := bar.BarMUS.Unmarshal(r)
	v = Zoo(v1)
	return
}

func (s zooMUS) Size(v Zoo) (size int) {
	return bar.BarMUS.Size(bar.Bar(v))
}

func (s zooMUS) Skip(r mus.Reader) (n int, err error) {
	return bar.BarMUS.Skip(r)
}
