// Code generated by the AI agent with mus-skill-go. DO NOT EDIT.

package multipackage

import (
	bar "github.com/mus-format/mus-skill-go/test/mus-go/multi-package/sub"
)

var FooMUS = fooMUS{}

type fooMUS struct{}

func (s fooMUS) Marshal(v Foo, bs []byte) (n int) {
	return bar.BarMUS.Marshal(v.Bar, bs)
}

func (s fooMUS) Unmarshal(bs []byte) (v Foo, n int, err error) {
	v.Bar, n, err = bar.BarMUS.Unmarshal(bs)
	return
}

func (s fooMUS) Size(v Foo) (size int) {
	return bar.BarMUS.Size(v.Bar)
}

func (s fooMUS) Skip(bs []byte) (n int, err error) {
	return bar.BarMUS.Skip(bs)
}

// -----------------------------------------------------------------------------

var ZooMUS = zooMUS{}

type zooMUS struct{}

func (s zooMUS) Marshal(v Zoo, bs []byte) (n int) {
	return bar.BarMUS.Marshal(bar.Bar(v), bs)
}

func (s zooMUS) Unmarshal(bs []byte) (v Zoo, n int, err error) {
	v1, n, err := bar.BarMUS.Unmarshal(bs)
	v = Zoo(v1)
	return
}

func (s zooMUS) Size(v Zoo) (size int) {
	return bar.BarMUS.Size(bar.Bar(v))
}

func (s zooMUS) Skip(bs []byte) (n int, err error) {
	return bar.BarMUS.Skip(bs)
}
