// Code generated by the AI agent with mus-gen-skill-go. DO NOT EDIT.

package bar

import (
	"github.com/mus-format/mus-go/ord"
)

var BarMUS = barMUS{}

type barMUS struct{}

func (s barMUS) Marshal(v Bar, bs []byte) (n int) {
	return ord.ByteSlice.Marshal(v.Sl, bs)
}

func (s barMUS) Unmarshal(bs []byte) (v Bar, n int, err error) {
	v.Sl, n, err = ord.ByteSlice.Unmarshal(bs)
	return
}

func (s barMUS) Size(v Bar) (size int) {
	return ord.ByteSlice.Size(v.Sl)
}

func (s barMUS) Skip(bs []byte) (n int, err error) {
	return ord.ByteSlice.Skip(bs)
}
