// Code generated by the AI agent with mus-gen-skill-go. DO NOT EDIT.

package definedtype

import (
	"github.com/mus-format/mus-stream-go"
	"github.com/mus-format/mus-stream-go/varint"
)

var FooMUS = fooMUS{}

type fooMUS struct{}

func (s fooMUS) Marshal(v Foo, w mus.Writer) (n int, err error) {
	return varint.Int.Marshal(int(v), w)
}

func (s fooMUS) Unmarshal(r mus.Reader) (v Foo, n int, err error) {
	v1, n, err := varint.Int.Unmarshal(r)
	v = Foo(v1)
	return
}

func (s fooMUS) Size(v Foo) (size int) {
	return varint.Int.Size(int(v))
}

func (s fooMUS) Skip(r mus.Reader) (n int, err error) {
	return varint.Int.Skip(r)
}
