// Code generated by the AI agent with mus-skill-go. DO NOT EDIT.

package definedtype

import (
	"testing"

	"github.com/mus-format/mus-stream-go/test"
)

func TestFoo(t *testing.T) {
	cases := []Foo{1, 2, 3, 0, -1}
	test.Test(cases, FooMUS, t)
	test.TestSkip(cases, FooMUS, t)
}
