// Code generated by AI agent with mus-skill. DO NOT EDIT.

package stream_notunsafe

import (
	"github.com/mus-format/mus-skill-go/test/mode"
	"github.com/mus-format/mus-stream-go"
	"github.com/mus-format/mus-stream-go/ord"
	"github.com/mus-format/mus-stream-go/unsafe"
)

// FullDefinedMUS
var FullDefinedMUS = fullDefinedMUS{}

type fullDefinedMUS struct{}

func (s fullDefinedMUS) Marshal(v mode.FullDefined, w mus.Writer) (n int, err error) {
	return unsafe.Int.Marshal(int(v), w)
}

func (s fullDefinedMUS) Unmarshal(r mus.Reader) (v mode.FullDefined, n int, err error) {
	tmp, n, err := unsafe.Int.Unmarshal(r)
	if err != nil {
		return
	}
	v = mode.FullDefined(tmp)
	return
}

func (s fullDefinedMUS) Size(v mode.FullDefined) (size int) {
	return unsafe.Int.Size(int(v))
}

func (s fullDefinedMUS) Skip(r mus.Reader) (n int, err error) {
	return unsafe.Int.Skip(r)
}

// FullInterfaceImplMUS
var FullInterfaceImplMUS = fullInterfaceImplMUS{}

type fullInterfaceImplMUS struct{}

func (s fullInterfaceImplMUS) Marshal(v mode.FullInterfaceImpl, w mus.Writer) (n int, err error) {
	return ord.String.Marshal(string(v), w)
}

func (s fullInterfaceImplMUS) Unmarshal(r mus.Reader) (v mode.FullInterfaceImpl, n int, err error) {
	tmp, n, err := ord.String.Unmarshal(r)
	if err != nil {
		return
	}
	v = mode.FullInterfaceImpl(tmp)
	return
}

func (s fullInterfaceImplMUS) Size(v mode.FullInterfaceImpl) (size int) {
	return ord.String.Size(string(v))
}

func (s fullInterfaceImplMUS) Skip(r mus.Reader) (n int, err error) {
	return ord.String.Skip(r)
}

// Anonymous serializers
var (
	ptrgyz6lfcPDFFKs3VdEsnvGQΞΞ   = ord.NewPtrSer(unsafe.Int)
	arraygyz6lfcPDFFKs3VdEsnvGQΞΞ = unsafe.NewArraySer[[10]int, int](unsafe.Int)
	slicegyz6lfcPDFFKs3VdEsnvGQΞΞ = ord.NewSliceSer(unsafe.Int)
	mapuQNcWTkkhDD2E1YGlud1YgΞΞ   = ord.NewMapSer(ord.String, unsafe.Int)
)

// FullStructMUS
var FullStructMUS = fullStructMUS{}

type fullStructMUS struct{}

func (s fullStructMUS) Marshal(v mode.FullStruct, w mus.Writer) (n int, err error) {
	var n1 int
	n1, err = unsafe.Int.Marshal(v.Int, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Int64.Marshal(v.Int64, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Int32.Marshal(v.Int32, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Int16.Marshal(v.Int16, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Int8.Marshal(v.Int8, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint.Marshal(v.Uint, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint64.Marshal(v.Uint64, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint32.Marshal(v.Uint32, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint16.Marshal(v.Uint16, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint8.Marshal(v.Uint8, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Float64.Marshal(v.Float64, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Float32.Marshal(v.Float32, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint8.Marshal(v.Byte, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Bool.Marshal(v.Bool, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.String.Marshal(v.Str, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.ByteSlice.Marshal(v.ByteSlice, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.ByteSlice.Marshal(v.Uint8Slice, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.TimeUnixUTC.Marshal(v.Time, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = ptrgyz6lfcPDFFKs3VdEsnvGQΞΞ.Marshal(v.PtrInt, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = arraygyz6lfcPDFFKs3VdEsnvGQΞΞ.Marshal(v.ArrayInt, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = slicegyz6lfcPDFFKs3VdEsnvGQΞΞ.Marshal(v.SliceInt, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = mapuQNcWTkkhDD2E1YGlud1YgΞΞ.Marshal(v.MapStrInt, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = FullDefinedMUS.Marshal(v.Defined, w)
	n += n1
	return
}

func (s fullStructMUS) Unmarshal(r mus.Reader) (v mode.FullStruct, n int, err error) {
	var n1 int
	v.Int, n1, err = unsafe.Int.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Int64, n1, err = unsafe.Int64.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Int32, n1, err = unsafe.Int32.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Int16, n1, err = unsafe.Int16.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Int8, n1, err = unsafe.Int8.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Uint, n1, err = unsafe.Uint.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Uint64, n1, err = unsafe.Uint64.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Uint32, n1, err = unsafe.Uint32.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Uint16, n1, err = unsafe.Uint16.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Uint8, n1, err = unsafe.Uint8.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Float64, n1, err = unsafe.Float64.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Float32, n1, err = unsafe.Float32.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Byte, n1, err = unsafe.Uint8.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Bool, n1, err = unsafe.Bool.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Str, n1, err = ord.String.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.ByteSlice, n1, err = ord.ByteSlice.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Uint8Slice, n1, err = ord.ByteSlice.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Time, n1, err = unsafe.TimeUnixUTC.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.PtrInt, n1, err = ptrgyz6lfcPDFFKs3VdEsnvGQΞΞ.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.ArrayInt, n1, err = arraygyz6lfcPDFFKs3VdEsnvGQΞΞ.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.SliceInt, n1, err = slicegyz6lfcPDFFKs3VdEsnvGQΞΞ.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.MapStrInt, n1, err = mapuQNcWTkkhDD2E1YGlud1YgΞΞ.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Defined, n1, err = FullDefinedMUS.Unmarshal(r)
	n += n1
	return
}

func (s fullStructMUS) Size(v mode.FullStruct) (size int) {
	size = unsafe.Int.Size(v.Int)
	size += unsafe.Int64.Size(v.Int64)
	size += unsafe.Int32.Size(v.Int32)
	size += unsafe.Int16.Size(v.Int16)
	size += unsafe.Int8.Size(v.Int8)
	size += unsafe.Uint.Size(v.Uint)
	size += unsafe.Uint64.Size(v.Uint64)
	size += unsafe.Uint32.Size(v.Uint32)
	size += unsafe.Uint16.Size(v.Uint16)
	size += unsafe.Uint8.Size(v.Uint8)
	size += unsafe.Float64.Size(v.Float64)
	size += unsafe.Float32.Size(v.Float32)
	size += unsafe.Uint8.Size(v.Byte)
	size += unsafe.Bool.Size(v.Bool)
	size += ord.String.Size(v.Str)
	size += ord.ByteSlice.Size(v.ByteSlice)
	size += ord.ByteSlice.Size(v.Uint8Slice)
	size += unsafe.TimeUnixUTC.Size(v.Time)
	size += ptrgyz6lfcPDFFKs3VdEsnvGQΞΞ.Size(v.PtrInt)
	size += arraygyz6lfcPDFFKs3VdEsnvGQΞΞ.Size(v.ArrayInt)
	size += slicegyz6lfcPDFFKs3VdEsnvGQΞΞ.Size(v.SliceInt)
	size += mapuQNcWTkkhDD2E1YGlud1YgΞΞ.Size(v.MapStrInt)
	size += FullDefinedMUS.Size(v.Defined)
	return size
}

func (s fullStructMUS) Skip(r mus.Reader) (n int, err error) {
	var n1 int
	n1, err = unsafe.Int.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Int64.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Int32.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Int16.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Int8.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint64.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint32.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint16.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint8.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Float64.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Float32.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint8.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Bool.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.String.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.ByteSlice.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.ByteSlice.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.TimeUnixUTC.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = ptrgyz6lfcPDFFKs3VdEsnvGQΞΞ.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = arraygyz6lfcPDFFKs3VdEsnvGQΞΞ.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = slicegyz6lfcPDFFKs3VdEsnvGQΞΞ.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = mapuQNcWTkkhDD2E1YGlud1YgΞΞ.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = FullDefinedMUS.Skip(r)
	n += n1
	return
}
