// Code generated by the AI agent with mus-gen-skill-go. DO NOT EDIT.

package complex

import (
	"github.com/mus-format/common-go"
	"github.com/mus-format/mus-gen-skill-go/test/mus-go/complex/sers"
	"github.com/mus-format/mus-gen-skill-go/test/mus-go/complex/validators"
	mapopts "github.com/mus-format/mus-go/options/map"
	slopts "github.com/mus-format/mus-go/options/slice"
	"github.com/mus-format/mus-go/ord"
	"github.com/mus-format/mus-go/raw"
	"github.com/mus-format/mus-go/varint"
)

// DTMs for MyInterface
const (
	Impl1DTM common.DTM = 1
	Impl2DTM common.DTM = 2
)

// Anonymous Serializers for Foo.sl ([][]string)
var (
	// inner slice: []string with element validation
	sliceYVq7QqbMyHΔ4Eh7HbZOLiAΞΞ = ord.NewValidSliceSer(
		ord.String,
		slopts.WithLenSer[string](raw.Int),
		slopts.WithElemValidator[string](common.ValidatorFn[string](validators.ValidateString)),
	)
	// outer slice: [][]string
	sliceeunΔGie8TxikacvtHiTkaQΞΞ = ord.NewSliceSer(
		sliceYVq7QqbMyHΔ4Eh7HbZOLiAΞΞ,
		slopts.WithLenSer[[]string](raw.Int),
	)
)

// Serializer for Foo
var ComplexFooMUS = complexFooMUS{}

type complexFooMUS struct{}

func (s complexFooMUS) Marshal(v Foo, bs []byte) (n int) {
	n = varint.Int.Marshal(v.Num, bs)
	n += raw.Int.Marshal(v.RawNum, bs[n:])
	n += ValidStringMUS.Marshal(v.Str, bs[n:])
	n += CustomSliceMUS.Marshal(v.Sl, bs[n:])
	n += CustomMapMUS.Marshal(v.Map, bs[n:])
	n += ord.NewPtrSer(varint.Int).Marshal(v.Ptr, bs[n:])
	n += sers.Bar1.Marshal(v.Bar1, bs[n:])
	n += sers.Bar2.Marshal(v.Bar2, bs[n:])
	n += sers.PointMUS.Marshal(v.Point, bs[n:])
	n += EmbeddedMUS.Marshal(v.Embedded, bs[n:])
	n += sliceeunΔGie8TxikacvtHiTkaQΞΞ.Marshal(v.sl, bs[n:])
	return
}

func (s complexFooMUS) Unmarshal(bs []byte) (v Foo, n int, err error) {
	var n1 int
	// Num
	v.Num, n, err = varint.Int.Unmarshal(bs)
	if err != nil {
		return
	}
	if err = validators.ValidateInt(v.Num); err != nil {
		return
	}
	// RawNum
	v.RawNum, n1, err = raw.Int.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	// Str
	v.Str, n1, err = ValidStringMUS.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	// Sl
	v.Sl, n1, err = CustomSliceMUS.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	// Map
	v.Map, n1, err = CustomMapMUS.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	// Ptr
	v.Ptr, n1, err = ord.NewPtrSer(varint.Int).Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	// Bar1
	v.Bar1, n1, err = sers.Bar1.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	// Bar2
	v.Bar2, n1, err = sers.Bar2.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	// Point
	v.Point, n1, err = sers.PointMUS.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	// Embedded
	v.Embedded, n1, err = EmbeddedMUS.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	// sl
	v.sl, n1, err = sliceeunΔGie8TxikacvtHiTkaQΞΞ.Unmarshal(bs[n:])
	n += n1
	return
}

func (s complexFooMUS) Size(v Foo) (size int) {
	size = varint.Int.Size(v.Num)
	size += raw.Int.Size(v.RawNum)
	size += ValidStringMUS.Size(v.Str)
	size += CustomSliceMUS.Size(v.Sl)
	size += CustomMapMUS.Size(v.Map)
	size += ord.NewPtrSer(varint.Int).Size(v.Ptr)
	size += sers.Bar1.Size(v.Bar1)
	size += sers.Bar2.Size(v.Bar2)
	size += sers.PointMUS.Size(v.Point)
	size += EmbeddedMUS.Size(v.Embedded)
	size += sliceeunΔGie8TxikacvtHiTkaQΞΞ.Size(v.sl)
	return
}

func (s complexFooMUS) Skip(bs []byte) (n int, err error) {
	var n1 int
	n, err = varint.Int.Skip(bs)
	if err != nil {
		return
	}
	n1, err = raw.Int.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = ValidStringMUS.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = CustomSliceMUS.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = CustomMapMUS.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.NewPtrSer(varint.Int).Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = sers.Bar1.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = sers.Bar2.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = sers.PointMUS.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = EmbeddedMUS.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = sliceeunΔGie8TxikacvtHiTkaQΞΞ.Skip(bs[n:])
	n += n1
	return
}

// -----------------------------------------------------------------------------

var ValidStringMUS = validStringMUS{}

type validStringMUS struct{}

func (s validStringMUS) Marshal(v ValidString, bs []byte) (n int) {
	return ord.String.Marshal(string(v), bs)
}

func (s validStringMUS) Unmarshal(bs []byte) (v ValidString, n int, err error) {
	var v1 string
	v1, n, err = ord.String.Unmarshal(bs)
	if err != nil {
		return
	}
	if err = validators.ValidateString(v1); err != nil {
		return
	}
	v = ValidString(v1)
	return
}

func (s validStringMUS) Size(v ValidString) (size int) {
	return ord.String.Size(string(v))
}

func (s validStringMUS) Skip(bs []byte) (n int, err error) {
	return ord.String.Skip(bs)
}

// -----------------------------------------------------------------------------

var CustomMapMUS = customMapMUS{}

type customMapMUS struct{}

var customMapSerializer = ord.NewValidMapSer(
	ord.String,               // Key serialization
	ord.NewSliceSer(raw.Int), // Value serialization
	mapopts.WithLenSer[string, []int](raw.Int),
	mapopts.WithKeyValidator[string, []int](common.ValidatorFn[string](validators.ValidateMapKey)),
)

func (s customMapMUS) Marshal(v CustomMap, bs []byte) (n int) {
	return customMapSerializer.Marshal(v, bs)
}

func (s customMapMUS) Unmarshal(bs []byte) (v CustomMap, n int, err error) {
	v1, n, err := customMapSerializer.Unmarshal(bs)
	v = CustomMap(v1)
	return
}

func (s customMapMUS) Size(v CustomMap) (size int) {
	return customMapSerializer.Size(v)
}

func (s customMapMUS) Skip(bs []byte) (n int, err error) {
	return customMapSerializer.Skip(bs)
}

// -----------------------------------------------------------------------------

var CustomSliceMUS = customSliceMUS{}

type customSliceMUS struct{}

var customSliceSerializer = ord.NewValidSliceSer(
	varint.Int,
	slopts.WithLenSer[int](raw.Int),
	slopts.WithElemValidator[int](common.ValidatorFn[int](validators.ValidateSliceElem)),
)

func (s customSliceMUS) Marshal(v CustomSlice, bs []byte) (n int) {
	return customSliceSerializer.Marshal(v, bs)
}

func (s customSliceMUS) Unmarshal(bs []byte) (v CustomSlice, n int, err error) {
	v1, n, err := customSliceSerializer.Unmarshal(bs)
	v = CustomSlice(v1)
	return
}

func (s customSliceMUS) Size(v CustomSlice) (size int) {
	return customSliceSerializer.Size(v)
}

func (s customSliceMUS) Skip(bs []byte) (n int, err error) {
	return customSliceSerializer.Skip(bs)
}

// -----------------------------------------------------------------------------

var EmbeddedMUS = embeddedMUS{}

type embeddedMUS struct{}

func (s embeddedMUS) Marshal(v Embedded, bs []byte) (n int) {
	return ord.Bool.Marshal(v.Bool, bs)
}

func (s embeddedMUS) Unmarshal(bs []byte) (v Embedded, n int, err error) {
	v.Bool, n, err = ord.Bool.Unmarshal(bs)
	return
}

func (s embeddedMUS) Size(v Embedded) (size int) {
	return ord.Bool.Size(v.Bool)
}

func (s embeddedMUS) Skip(bs []byte) (n int, err error) {
	return ord.Bool.Skip(bs)
}

// -----------------------------------------------------------------------------

var MyInterfaceMUS = myInterfaceMUS{}

type myInterfaceMUS struct{}

func (s myInterfaceMUS) Marshal(v MyInterface, bs []byte) (n int) {
	switch v1 := v.(type) {
	case Impl1:
		n = varint.Uint64.Marshal(uint64(Impl1DTM), bs)
		n += Impl1MUS.Marshal(v1, bs[n:])
	case Impl2:
		n = varint.Uint64.Marshal(uint64(Impl2DTM), bs)
		n += Impl2MUS.Marshal(v1, bs[n:])
	case *Impl1:
		n = varint.Uint64.Marshal(uint64(Impl1DTM), bs)
		n += Impl1MUS.Marshal(*v1, bs[n:])
	case *Impl2:
		n = varint.Uint64.Marshal(uint64(Impl2DTM), bs)
		n += Impl2MUS.Marshal(*v1, bs[n:])
	default:
		panic("unknown implementation")
	}
	return
}

func (s myInterfaceMUS) Unmarshal(bs []byte) (v MyInterface, n int, err error) {
	var (
		dtm uint64
		n1  int
	)
	dtm, n, err = varint.Uint64.Unmarshal(bs)
	if err != nil {
		return
	}
	switch common.DTM(dtm) {
	case Impl1DTM:
		var impl Impl1
		impl, n1, err = Impl1MUS.Unmarshal(bs[n:])
		v = impl
	case Impl2DTM:
		var impl Impl2
		impl, n1, err = Impl2MUS.Unmarshal(bs[n:])
		v = impl
	default:
		err = common.ErrUnknownDTM
	}
	n += n1
	return
}

func (s myInterfaceMUS) Size(v MyInterface) (size int) {
	switch v1 := v.(type) {
	case Impl1:
		size = varint.Uint64.Size(uint64(Impl1DTM))
		size += Impl1MUS.Size(v1)
	case Impl2:
		size = varint.Uint64.Size(uint64(Impl2DTM))
		size += Impl2MUS.Size(v1)
	case *Impl1:
		size = varint.Uint64.Size(uint64(Impl1DTM))
		size += Impl1MUS.Size(*v1)
	case *Impl2:
		size = varint.Uint64.Size(uint64(Impl2DTM))
		size += Impl2MUS.Size(*v1)
	default:
		panic("unknown implementation")
	}
	return
}

func (s myInterfaceMUS) Skip(bs []byte) (n int, err error) {
	var (
		dtm uint64
		n1  int
	)
	dtm, n, err = varint.Uint64.Unmarshal(bs)
	if err != nil {
		return
	}
	switch common.DTM(dtm) {
	case Impl1DTM:
		n1, err = Impl1MUS.Skip(bs[n:])
	case Impl2DTM:
		n1, err = Impl2MUS.Skip(bs[n:])
	default:
		err = common.ErrUnknownDTM
	}
	n += n1
	return
}

// -----------------------------------------------------------------------------

var Impl1MUS = impl1MUS{}

type impl1MUS struct{}

func (s impl1MUS) Marshal(v Impl1, bs []byte) (n int) {
	return varint.Int.Marshal(v.A, bs)
}

func (s impl1MUS) Unmarshal(bs []byte) (v Impl1, n int, err error) {
	v.A, n, err = varint.Int.Unmarshal(bs)
	return
}

func (s impl1MUS) Size(v Impl1) (size int) {
	return varint.Int.Size(v.A)
}

func (s impl1MUS) Skip(bs []byte) (n int, err error) {
	return varint.Int.Skip(bs)
}

// -----------------------------------------------------------------------------

var Impl2MUS = impl2MUS{}

type impl2MUS struct{}

func (s impl2MUS) Marshal(v Impl2, bs []byte) (n int) {
	return ord.String.Marshal(v.B, bs)
}

func (s impl2MUS) Unmarshal(bs []byte) (v Impl2, n int, err error) {
	v.B, n, err = ord.String.Unmarshal(bs)
	return
}

func (s impl2MUS) Size(v Impl2) (size int) {
	return ord.String.Size(v.B)
}

func (s impl2MUS) Skip(bs []byte) (n int, err error) {
	return ord.String.Skip(bs)
}
