// Code generated by the AI agent with mus-gen-skill-go. DO NOT EDIT.

package complex

import (
	"image"
	"testing"

	"github.com/mus-format/mus-gen-skill-go/test/mus-go/complex/sub1"
	"github.com/mus-format/mus-gen-skill-go/test/mus-go/complex/sub2"
	"github.com/mus-format/mus-gen-skill-go/test/mus-go/complex/validators"
	"github.com/mus-format/mus-go/test"
)

func TestComplex(t *testing.T) {
	// Foo
	t.Run("Foo", func(t *testing.T) {
		num := 10
		cases := []Foo{
			{
				Num:      1,
				RawNum:   2,
				Str:      "valid",
				Sl:       CustomSlice{1, 2, 3},
				Map:      CustomMap{"k": {4, 5}},
				Ptr:      &num,
				Bar1:     sub1.Bar{Int: 100},
				Bar2:     sub2.Bar{Str: "bar2"},
				Point:    image.Point{X: 10, Y: 20},
				Embedded: Embedded{Bool: true},
				sl:       [][]string{{"a", "b"}, {"c"}},
			},
			{
				Str: "valid",
				Sl:  CustomSlice{},
				Map: CustomMap{},
				sl:  [][]string{},
			},
		}
		test.Test(cases, ComplexFooMUS, t)
		test.TestSkip(cases, ComplexFooMUS, t)

		// Validation
		t.Run("Validation", func(t *testing.T) {
			// Success
			test.TestValidation(cases[0], ComplexFooMUS, nil, t)
			// Failure (Num)
			test.TestValidation(Foo{Num: -1}, ComplexFooMUS, validators.ErrNegativeInt, t)
			// Failure (Str)
			test.TestValidation(Foo{Num: 1, Str: ""}, ComplexFooMUS, validators.ErrEmptyString, t)
			// Failure (Sl)
			test.TestValidation(Foo{Num: 1, Str: "v", Sl: CustomSlice{-1}}, ComplexFooMUS, validators.ErrNegativeSliceElem, t)
			// Failure (Map)
			test.TestValidation(Foo{Num: 1, Str: "v", Map: CustomMap{"": {1}}}, ComplexFooMUS, validators.ErrEmptyMapKey, t)
			// Failure (sl)
			test.TestValidation(Foo{Num: 1, Str: "v", sl: [][]string{{""}}}, ComplexFooMUS, validators.ErrEmptyString, t)
		})
	})

	// ValidString
	t.Run("ValidString", func(t *testing.T) {
		test.TestValidation(ValidString("valid"), ValidStringMUS, nil, t)
		test.TestValidation(ValidString(""), ValidStringMUS, validators.ErrEmptyString, t)
	})

	// CustomSlice
	t.Run("CustomSlice", func(t *testing.T) {
		test.TestValidation(CustomSlice{1, 2}, CustomSliceMUS, nil, t)
		test.TestValidation(CustomSlice{-1}, CustomSliceMUS, validators.ErrNegativeSliceElem, t)
	})

	// CustomMap
	t.Run("CustomMap", func(t *testing.T) {
		test.TestValidation(CustomMap{"k": {1}}, CustomMapMUS, nil, t)
		test.TestValidation(CustomMap{"": {1}}, CustomMapMUS, validators.ErrEmptyMapKey, t)
	})

	// MyInterface
	t.Run("MyInterface", func(t *testing.T) {
		cases := []MyInterface{
			Impl1{A: 1},
			Impl2{B: "2"},
		}
		test.Test(cases, MyInterfaceMUS, t)
		test.TestSkip(cases, MyInterfaceMUS, t)
	})
}
