// Code generated by AI agent with mus-skill. DO NOT EDIT.

package pkg4

import (
	"testing"

	"github.com/mus-format/mus-go/test"
	"github.com/mus-format/mus-skill-go/test/genopts/cross-package/pkg3"
)

func TestFoo(t *testing.T) {
	cases := []pkg3.Foo{0, 1, -1, 100}
	test.Test(cases, FooMUS, t)
	test.TestSkip(cases, FooMUS, t)
}
