// Code generated by AI agent with mus-skill. DO NOT EDIT.

package pkg4

import (
	"github.com/mus-format/mus-go/varint"
	"github.com/mus-format/mus-skill-go/test/genopts/cross-package/pkg3"
)

// FooMUS
var FooMUS = fooMUS{}

type fooMUS struct{}

func (s fooMUS) Marshal(v pkg3.Foo, bs []byte) (n int) {
	return varint.Int.Marshal(int(v), bs)
}

func (s fooMUS) Unmarshal(bs []byte) (v pkg3.Foo, n int, err error) {
	tmp, n, err := varint.Int.Unmarshal(bs)
	if err != nil {
		return
	}
	v = pkg3.Foo(tmp)
	return
}

func (s fooMUS) Size(v pkg3.Foo) (size int) {
	return varint.Int.Size(int(v))
}

func (s fooMUS) Skip(bs []byte) (n int, err error) {
	return varint.Int.Skip(bs)
}
